import { TermInJson } from "../types";

export const gen3Glossary: TermInJson[] = [
  {
    name: "Semilla",
    url: "https://en.wikipedia.org/wiki/Random_seed",
    aliases: ["Semilla inicial"],
    importance: 5,
    desc: "Valor inicial usado por el generador de números aleatorios (RNG) del juego.  Conociéndolo o controlándolo permite a los jugadores el predecir y manipular la aleatoriedad del juego para resultados deseados.",
  },
  {
    name: "Avance",
    importance: 5,
    desc: "Proceso de moverse hacia adelante en la secuencia del número aleatorio del juego. Esto sucede a través de acciones en el juego como movimientos de NPS, interacciones en el menú, o mecánicas específicas que cambian el RNG a un nuevo estado.",
  },
  {
    name: "Avance objetivo",
    importance: 5,
    desc: "Avance específico del RNG que un jugador busca para obtener el resultado deseado. Ej.: Avance 1000 para un Pokémon brillante.",
  },
  {
    name: "Avance obtenido",
    importance: 5,
    desc: "Avance específico del RNG que un jugador obtuvo al intentar manipularlo. Usualmente es desplegado junto con la diferencia de tu avance objetivo. Ej.: Avance 1007 (+7), cuando el avance objetivo es 1000.",
  },
  {
    name: "Fotograma",
    importance: 5,
    desc: "Imagen individual renderizada en la pantalla, que se actualiza a una frecuencia constante (~59.7 fotogramas por segundo en GBA).",
    aliases: ["Fotograma visual"],
  },
  {
    name: "Calibración (acción)",
    importance: 5,
    desc: "Proceso de determinación de las inconsistencias de tiempo del juego para predecir con precisión los resultados del RNG.",
  },
  {
    name: "Calibración (valor)",
    importance: 5,
    desc: "Variación de tiempo para compensar las inconsistencias del juego y obtener el resultado deseado. Ej.: +100 ms.",
  },
  {
    name: "Desfase",
    importance: 5,
    desc: "La diferencia entre el avance del RNG entre la última acción realizada por el jugador y el momento en que se genera el Pokémon. Ej.: Si el desfase es 5 y pulsas A en el avance 1000, el Pokémon se generará en el avance 1005.",
  },
  {
    name: "Valor individual",
    url: "https://bulbapedia.bulbagarden.net/wiki/Individual_values",
    aliases: ["IV"],
    importance: 5,
    desc: "Numero generado aleatoriamente (0-31) que se asigna a un Pokémon al generarse. Hay uno para cada estadística e influye en su valor real.",
  },
  {
    name: "Hexadecimal",
    aliases: ["Hex"],
    importance: 4,
    desc: "Sistema de numeración de base 16, donde cada dígito puede representar un valor del 0 al 15. Utiliza los dígitos del 0 al 9 y las letras de la A a la F para representar los valores del 10 al 15.",
  },
  {
    name: "Modulo",
    aliases: ["Mod"],
    importance: 4,
    desc: "Operación matemática para obtener el residuo de dividir un número entre otro. Por ejemplo, 5 mod 3 = 2, ya que al dividir 5 entre 3, el residuo es 2.",
  },
  {
    name: "ID de entrenador",
    url: "https://bulbapedia.bulbagarden.net/wiki/Trainer_ID_number",
    aliases: ["TID"],
    importance: 4,
    desc: "Número aleatorio generado al iniciar una nueva partida. Se muestra en la tarjeta de entrenador. Afecta si un Pokémon es brillante o no.",
  },
  {
    name: "ID secreto de entrenador",
    url: "https://bulbapedia.bulbagarden.net/wiki/Trainer_ID_number#Secret_ID",
    aliases: ["SID"],
    importance: 4,
    desc: "Número aleatorio generado al iniciar una nueva partida. Nunca se muestra al jugador. Afecta si un Pokémon es brillante o no.",
  },
  {
    name: "Valor brillante del",
    aliases: ["TSV"],
    importance: 4,
    desc: "Número derivado del ID de Entrenador y el ID Secreto. Un Pokémon es brillante si su valor brillante es igual al valor brillante del entrenador original.",
  },
  {
    name: "Valor de personalidad",
    url: "https://bulbapedia.bulbagarden.net/wiki/Personality_value",
    aliases: ["PID"],
    importance: 4,
    desc: "Número aleatorio generado para cada Pokémon. Determina el género, la habilidad, la naturaleza y si es brillante. Los valores de personalidad se escriben en formato hexadecimal (ej.: ABCD1234).",
  },
  {
    name: "Valor brillante del",
    aliases: ["PSV", "Valor brillante de huevo", "ESV"],
    importance: 4,
    desc: "Número derivado del valor de personalidad Pokémon. Un Pokémon es brillante si su valor brillante es igual al valor brillante del entrenador original.",
  },
  {
    name: "Batería muerta",
    aliases: ["Pila seca"],
    importance: 4,
    desc: "Reloj interno del juego  que ya no funciona. En Rubí y Zafiro, esto hace que el RNG comience desde una semilla fija cada vez que se inicia el juego. Esto facilita la manipulación del RNG, ya que los jugadores pueden predecir y controlar los encuentros Pokémon de forma más consistente.",
  },
  {
    name: "Batería viva",
    importance: 4,
    desc: "Reloj interno del juego en funcionamiento. En Rubí y Zafiro, esto hace que el RNG comience desde una semilla diferente cada vez que se inicia el juego.",
  },
  {
    name: "Dulce aroma",
    url: "https://bulbapedia.bulbagarden.net/wiki/Sweet_Scent_(move)",
    importance: 4,
    desc: "Ataque que puede ser usado fuera de una combate para iniciar un encuentro con un Pokémon salvaje. Su consistencia lo hace ideal para la manipulación del RNG.",
  },
  {
    name: "Sincronía",
    url: "https://bulbapedia.bulbagarden.net/wiki/Synchronize_(Ability)",
    importance: 4,
    desc: "En Pokémon Esmeralda, los encuentros con Pokémon salvajes tienen un 50% de probabilidad de compartir la misma Naturaleza que el Pokémon principal si tiene la habilidad Sincronía.",
  },

  {
    name: "Mystic Timer",
    url: "/mystic-timer",
    importance: 4,
    desc: "Temporizador diseñado específicamente para la manipulación del RNG de Pokémon, disponible en un navegador de internet.",
  },
  {
    name: "Eon Timer",
    url: "https://github.com/DasAmpharos/EonTimer/releases",
    importance: 4,
    desc: "Temporizador diseñado específicamente para la manipulación del RNG de Pokémon, disponible como programa.",
  },
  {
    name: "Pokémon estático",
    importance: 4,
    desc: "Encuentros Pokémon que son predeterminados como iniciales, estacionarios, regalos, legendarios y errantes.",
  },
  {
    name: "Método",
    url: "/gba-methods",
    importance: 4,
    desc: "Un método indica cómo se generará un Pokémon para un avance determinado del RNG.",
    aliases: ["Método-1", "Método-4"],
  },
  {
    name: "Método-X",
    url: "/gba-methods",
    importance: 4,
    desc: "El método 1 y el método 4 son los métodos para Pokémon estáticos.",
  },
  {
    name: "Salvaje-X",
    url: "/gba-methods",
    importance: 4,
    desc: "Salvaje-1, Salvaje-2 y Salvaje-4 son los métodos para Pokémon salvajes.",
  },
  {
    name: "Lua script",
    url: "/mgba-setup",
    importance: 3,
    desc: "Un archivo con la extensión .lua que los emuladores pueden cargar para manipular el RNG, Ej.: Mostrar el avance actual del RNG.",
  },
  {
    name: "Resemillado",
    url: "/emerald-painting-rng",
    importance: 3,
    desc: "Se reinicia el estado del RNG con una nueva semilla, lo que permite saltar la secuencia aleatoria de números del juego. La pintura y el vídeo de batalla son técnicas basadas en la resemillado.",
  },
  {
    name: "Técnica de la pintura",
    url: "/emerald-painting-rng",
    importance: 3,
    desc: "Técnica para acortar el tiempo de espera para alcanzar avances altos del RNG al interactuar con una pintura en la Sala de Concursos de ciudad Calagua (Lilycove). Exclusiva de Pokémon Rubí, Zafiro y Esmeralda.",
  },
  {
    name: "Técnica de video de batalla",
    importance: 3,
    desc: "Técnica para acelerar los intentos repetidos de manipulación del RNG grabando un video de batalla y viéndolo para avanzar el RNG.",
  },
  {
    name: "Ruido",
    importance: 3,
    desc: "Factores impredecibles que causan que el RNG avance en maneras que son difíciles de controlar.",
  },
  {
    name: "mGBA",
    url: "/mgba-setup",
    importance: 3,
    desc: "Emulador de GBA con soporte de lua script, recomendado para manipulación de RNG.",
  },
  {
    name: "Valores de esfuerzo",
    url: "https://bulbapedia.bulbagarden.net/wiki/Effort_values",
    aliases: ["EV"],
    importance: 2,
    desc: "Experiencia de estadística oculta que se otorga tras derrotar Pokémon o consumir vitaminas. Influye en el valor real de las estadísticas. Rara vez es relevante en manipulaciones de RNG.",
  },
  {
    name: "NO$GBA",
    url: "https://problemkaputt.de/gba.htm",
    importance: 2,
    desc: "Emulador de GBA con un depurador interactivo incorporado que resulta útil para la investigación de manipulación de RNG.",
  },
  {
    name: "Dolphin",
    url: "https://dolphin-emu.org/",
    importance: 2,
    desc: "Emulador de GameCube con conectividad con GBA.",
  },
  {
    name: "PKHex",
    url: "https://github.com/kwsch/PKHeX",
    importance: 2,
    desc: "Editor de partidas de Pokémon.",
  },
  {
    name: "Ejecución de código Arbitrario",
    url: "https://bulbapedia.bulbagarden.net/wiki/Arbitrary_code_execution#Pok%C3%A9mon_Emerald",
    importance: 2,
    desc: "Vulnerabilidad que permite a los jugadores alterar el código de generación de Pokémon.",
    aliases: ["ACE"],
  },
  {
    name: "VBlank",
    url: "/gba-vblank",
    importance: 2,
    desc: "Mecanismo utilizado por GBA para actualizar la pantalla (aproximadamente 59,7 veces por segundo). VBlank actualiza el RNG para avanzar por 1.",
  },
  {
    name: "Contador de Ciclo",
    url: "/gba-vblank",
    importance: 2,
    desc: "Contador interno de GBA que registra el numero de instrucciones de CPU ejecutadas. Cada vez que alcanza 280'896, se activa un VBlank.",
  },
  {
    name: "Código decompilado",
    url: "https://github.com/pret",
    importance: 2,
    desc: "Código legible equivalente al programa del juego Pokémon. Se utiliza para comprender mejor su lógica.",
    aliases: ["pret"],
  },
];
