import { TermInJson } from "../types";

export const gen3Glossary: TermInJson[] = [
  {
    name: "Seed",
    url: "https://en.wikipedia.org/wiki/Random_seed",
    aliases: ["Initial seed"],
    importance: 5,
    desc: "Starting value used by the game's random number generator (RNG). Knowing or controlling it allows players to predict and manipulate in-game randomness for desired outcomes.",
  },
  {
    name: "Advance",
    importance: 5,
    desc: "Process of moving forward in the game's random number sequence. This happens through in-game actions like NPC movement, menu interactions, or specific mechanics that shift the RNG to a new state.",
  },
  {
    name: "Target advance",
    importance: 5,
    desc: "Specific RNG advance a player aims for a desired outcome. Ex: Advance 1000 for shiny Pokémon.",
  },
  {
    name: "Hit advance",
    importance: 5,
    desc: "Specific RNG advance a player actually hit when attempting an RNG manipulation. It is usually displayed along the difference with the target advance. Ex: Advance 1007 (+7), where the target advance is 1000.",
  },
  {
    name: "Frame",
    importance: 5,
    desc: "Single rendered image on the screen, which updates at a consistent rate (~59.7 frames per second on GBA).",
    aliases: ["Visual frame"],
  },
  {
    name: "Calibration (action)",
    importance: 5,
    desc: "Process of determining the game's timing inconsistencies to accurately predict RNG outcomes.",
  },
  {
    name: "Calibration (value)",
    importance: 5,
    desc: "Timing variation to counterbalance the game inconsistencies in order to obtain the desired outcome. Ex: +100 ms.",
  },
  {
    name: "Offset",
    importance: 5,
    desc: "The difference between the RNG advance on the last player input and when the Pokémon generation occurs. Ex: If the offset is 5 and you press A on advance 1000, the Pokémon will be generated on advance 1005.",
  },
  {
    name: "Individual value",
    url: "https://bulbapedia.bulbagarden.net/wiki/Individual_values",
    aliases: ["IV"],
    importance: 5,
    desc: "Randomly generated number (0-31) assigned to a Pokémon when it is generated. There is one for each stat and it influences the actual stat value. ",
  },
  {
    name: "Hexadecimal",
    aliases: ["Hex"],
    importance: 4,
    desc: "Base-16 numbering system where each digit can represent a value from 0 to 15. It uses the digits 0-9 and the letters A-F to represent the values 10-15. ",
  },
  {
    name: "Modulo",
    aliases: ["Mod"],
    importance: 4,
    desc: "Mathematic operation to get the remainder when one number is divided by another. For example, 5 mod 3 = 2 because when you divide 5 by 3, the remainder is 2.",
  },
  {
    name: "Trainer ID",
    url: "https://bulbapedia.bulbagarden.net/wiki/Trainer_ID_number",
    aliases: ["TID"],
    importance: 4,
    desc: "Random number generated when starting a new game. It is displayed on their trainer card. It affects whether a Pokémon is shiny.",
  },
  {
    name: "Secret ID",
    url: "https://bulbapedia.bulbagarden.net/wiki/Trainer_ID_number#Secret_ID",
    aliases: ["SID"],
    importance: 4,
    desc: "Random number generated when starting a new game. It is never displayed to the player. It affects whether a Pokémon is shiny.",
  },
  {
    name: "Trainer shiny value",
    aliases: ["TSV"],
    importance: 4,
    desc: "Number derived from the Trainer ID and Secret ID. A Pokémon is shiny if its Pokémon shiny value is the same of the original trainer's Trainer shiny value.",
  },
  {
    name: "Personality value",
    url: "https://bulbapedia.bulbagarden.net/wiki/Personality_value",
    aliases: ["PID"],
    importance: 4,
    desc: "Random number generated for each Pokémon. It determines the gender, ability, nature, and shininess. Personality values are written in hexadecimal format (ex: ABCD1234).",
  },
  {
    name: "Pokémon shiny value",
    aliases: ["PSV", "Egg shiny value", "ESV"],
    importance: 4,
    desc: "Number derived from the Pokémon Personality value. A Pokémon is shiny if its Pokémon shiny value is the same of the original trainer's Trainer shiny value.",
  },
  {
    name: "Dead battery",
    aliases: ["Dry battery"],
    importance: 4,
    desc: "No longer functioning game's internal clock. In Ruby & Sapphire, this causes the RNG to start from a fixed seed every time the game boots up. This makes RNG manipulation easier, as players can predict and control Pokémon encounters more consistently.",
  },
  {
    name: "Live battery",
    importance: 4,
    desc: "Functioning game's internal clock. In Ruby & Sapphire, this causes the RNG to start from a different seed every time the game boots up.",
  },
  {
    name: "Sweet Scent",
    url: "https://bulbapedia.bulbagarden.net/wiki/Sweet_Scent_(move)",
    importance: 4,
    desc: "Attack that can be used outside of battle to trigger a wild Pokémon encounter. Its consistency makes it ideal for RNG manipulation.",
  },
  {
    name: "Synchronize",
    url: "https://bulbapedia.bulbagarden.net/wiki/Synchronize_(Ability)",
    importance: 4,
    desc: "In Pokémon Emerald, wild Pokémon encounters have 50% chance to share the same Nature as the lead Pokémon if it has the Synchronize ability.",
  },

  {
    name: "Mystic Timer",
    url: "/mystic-timer",
    importance: 4,
    desc: "Timer specifically designed for Pokémon RNG manipulation, available in a browser.",
  },
  {
    name: "Eon Timer",
    url: "https://github.com/DasAmpharos/EonTimer/releases",
    importance: 4,
    desc: "Timer specifically designed for Pokémon RNG manipulation, available as a program.",
  },
  {
    name: "Static Pokémon",
    importance: 4,
    desc: "Pokémon encounters that predetermined such as starter, stationary, gift, legendary, and roamers Pokémon.",
  },
  {
    name: "Method",
    url: "/gba-methods",
    importance: 4,
    desc: "A method indicates how a Pokémon will be generated for a given RNG advance.",
    aliases: ["Method-1", "Method-4"],
  },
  {
    name: "Method-X",
    url: "/gba-methods",
    importance: 4,
    desc: "Method-1 and Method-4 are the methods for Static Pokémon.",
  },
  {
    name: "Wild-X",
    url: "/gba-methods",
    importance: 4,
    desc: "Wild-1, Wild-2 and Wild-4 are the methods for wild Pokémon.",
  },
  {
    name: "Lua script",
    url: "/mgba-setup",
    importance: 3,
    desc: "A file with the .lua extension that can be loaded by emulators to help manipulate RNG. Ex: Display the current RNG advance.",
  },
  {
    name: "Reseeding",
    url: "/emerald-painting-rng",
    importance: 3,
    desc: "Resetting the RNG state with a new seed, effectively jumping in the game's random number sequence. Painting and battle video are techniques based on reseeding.",
  },
  {
    name: "Painting technique",
    url: "/emerald-painting-rng",
    importance: 3,
    desc: "Technique to shorthen the wait time to reach high RNG advances by interacting with a painting in the Lilycove Contest Hall. Exclusive to Ruby, Sapphire, and Emerald.",
  },
  {
    name: "Battle video technique",
    importance: 3,
    desc: "Technique to speed up repeated RNG manipulation attempts by recording a battle video and viewing it to advance the RNG.",
  },
  {
    name: "Noise",
    importance: 3,
    desc: "Unpredictable factors that cause the RNG to advance in ways that are difficult to control.",
  },
  {
    name: "mGBA",
    url: "/mgba-setup",
    importance: 3,
    desc: "GBA emulator with lua script support which is recommended for RNG manipulation.",
  },
  {
    name: "Effort value",
    url: "https://bulbapedia.bulbagarden.net/wiki/Effort_values",
    aliases: ["EV"],
    importance: 2,
    desc: "Hidden stat experience given after defeating Pokémon or eating Vitamins. It influences the actual stat value. It is rarely relevant in RNG manipulations.",
  },
  {
    name: "NO$GBA",
    url: "https://problemkaputt.de/gba.htm",
    importance: 2,
    desc: "GBA emulator with a built-in interactive debugger which is useful for RNG manipulation research.",
  },
  {
    name: "Dolphin",
    url: "https://dolphin-emu.org/",
    importance: 2,
    desc: "GameCube emulator with GBA connectivity.",
  },
  {
    name: "PKHex",
    url: "https://github.com/kwsch/PKHeX",
    importance: 2,
    desc: "Pokémon save editor.",
  },
  {
    name: "Arbitrary code execution",
    url: "https://bulbapedia.bulbagarden.net/wiki/Arbitrary_code_execution#Pok%C3%A9mon_Emerald",
    importance: 2,
    desc: "Exploit allowing players to alter the Pokémon generation code.",
    aliases: ["ACE"],
  },
  {
    name: "VBlank",
    url: "/gba-vblank",
    importance: 2,
    desc: "Mechanism used by the GBA to refresh the screen (~59.7 times per second). VBlank updates the RNG to advance by 1.",
  },
  {
    name: "Cycle counter",
    url: "/gba-vblank",
    importance: 2,
    desc: "Internal counter in the GBA that tracks the number of CPU instructions performed. Every time it reaches 280'896, a VBlank is triggered.",
  },
  {
    name: "Decompiled code",
    url: "https://github.com/pret",
    importance: 2,
    desc: "Human-readable code equivalent to the Pokémon game program. It is used to better understand its logic.",
    aliases: ["pret"],
  },
];
