//! Runtime data structures used by the tool.
//!
//! These types don't implement `Deserialize` and don't use `Vec`. Instead,
//! they store data in `&'static [T]`, allowing them to be embedded directly
//! into the binary as static values. This avoids any memory allocation or
//! JSON parsing when the tool starts.
//!
//! The actual data is generated by `src/bin/generate_wild4.rs`. That generator
//! reads the original JSON only once during development/build time and produces
//! `src/gen4/generated_wild4.rs`, which contains the fully initialized static
//! data used at runtime.
//!
//! `location` and `species` are now `&'static str` (the JSON stores names
//! directly, there's no more numeric id + separate name-lookup file).
//!
//! The encounter resolution logic (`resolve_grass`, `resolve_water`, etc.)
//! remains exactly the same as before. It still depends on `Conditions`, which
//! are only available at runtime (active swarms, time of day, radar state,
//! and so on), so this logic can't be precomputed by the generator. What the
//! generator removes is the JSON parsing and struct conversion step, while the
//! game logic itself stays unchanged.

use crate::gen4::generated_wild4;
use crate::gen4::honey_tree::{HoneyTreeLocation, get_muchlax_trees};

#[derive(Debug, Clone, Copy)]
pub struct RawEntry {
    pub location: &'static str,
    pub rates: RawRates,
    pub grass: &'static [RawGrassSlot],
    pub swarm: &'static [&'static str],
    pub day: &'static [&'static str],
    pub night: &'static [&'static str],
    pub radar: &'static [&'static str],
    pub form: &'static [u8],
    pub dual_slot: RawDualSlot,
    pub surf: &'static [RawWaterSlot],
    pub old_rod: &'static [RawWaterSlot],
    pub good_rod: &'static [RawWaterSlot],
    pub super_rod: &'static [RawWaterSlot],
}

#[derive(Debug, Clone, Copy)]
pub struct RawRates {
    pub grass: u32,
    pub surf: u32,
    pub old_rod: u32,
    pub good_rod: u32,
    pub super_rod: u32,
}

#[derive(Debug, Clone, Copy)]
pub struct RawGrassSlot {
    pub species: &'static str,
    pub level: u8,
}

#[derive(Debug, Clone, Copy)]
pub struct RawWaterSlot {
    pub species: &'static str,
    pub min_level: u8,
    pub max_level: u8,
}

#[derive(Debug, Clone, Copy)]
pub struct RawDualSlot {
    pub ruby: &'static [&'static str],
    pub sapphire: &'static [&'static str],
    pub emerald: &'static [&'static str],
    pub firered: &'static [&'static str],
    pub leafgreen: &'static [&'static str],
}

#[derive(Debug, Clone, Copy)]
pub struct RawHoneyEntry {
    pub location: &'static str,
    pub normal: &'static [RawWaterSlot],
    pub rare: &'static [RawWaterSlot],
    pub munchlax: &'static [RawWaterSlot],
}

const GRASS_SLOT_RATES: [u32; 12] = [20, 20, 10, 10, 10, 10, 5, 5, 4, 4, 1, 1];
const WATER_SLOT_RATES: [u32; 5] = [60, 30, 5, 4, 1];

const MT_CORONET_B1F_LOCATION: &str = "Mt Coronet Upper B1F";
const FEEBAS_SPECIES: &str = "Feebas";
const FEEBAS_MIN_LEVEL: u8 = 10;
const FEEBAS_MAX_LEVEL: u8 = 20;

const SHELLOS_SPECIES: &str = "Shellos";
const GASTRODON_SPECIES: &str = "Gastrodon";

const FEEBAS_RATE_PERCENT_WHEN_TILE: u32 = 50;

const HONEY_TREE_MAP_IDS: [&str; 21] = [
    "Route 205 (South)",
    "Route 205 (North)",
    "Route 206",
    "Route 207",
    "Route 208",
    "Route 209",
    "Route 210 (South)",
    "Route 210 (North)",
    "Route 211 (East)",
    "Route 212 (North)",
    "Route 212 (South)",
    "Route 213",
    "Route 214",
    "Route 215",
    "Route 218",
    "Route 221",
    "Route 222",
    "Valley Windworks",
    "Eterna Forest",
    "Fuego Ironworks",
    "Floaroma Meadow",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Game {
    Diamond,
    Pearl,
    Platinum,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Method {
    Grass,
    Surf,
    OldRod,
    GoodRod,
    SuperRod,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TimeOfDay {
    Day,
    Night,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DualSlotCartridge {
    Ruby,
    Sapphire,
    Emerald,
    FireRed,
    LeafGreen,
}

#[derive(Debug, Clone, Default)]
pub struct Conditions {
    pub time_of_day: Option<TimeOfDay>,
    pub swarm_active: bool,
    pub radar_active: bool,
    pub dual_slot: Option<DualSlotCartridge>,
    pub feebas_tile: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResolvedEncounter {
    pub species: &'static str,
    pub form: u8,
    pub min_level: u8,
    pub max_level: u8,
    pub rate_percent: u32,
    pub slot: usize,
}

fn encounters_for(game: Game) -> &'static [RawEntry] {
    match game {
        Game::Diamond => generated_wild4::DIAMOND_ENTRIES,
        Game::Pearl => generated_wild4::PEARL_ENTRIES,
        Game::Platinum => generated_wild4::PLATINUM_ENTRIES,
    }
}

fn honey_for(game: Game) -> &'static [RawHoneyEntry] {
    match game {
        Game::Diamond => generated_wild4::DIAMOND_HONEY,
        Game::Pearl => generated_wild4::PEARL_HONEY,
        Game::Platinum => generated_wild4::PLATINUM_HONEY,
    }
}

pub fn get_wild_pokemon(
    game: Game,
    location: &str,
    method: Method,
    cond: &Conditions,
) -> Vec<ResolvedEncounter> {
    get_wild_pokemon_from_entries(encounters_for(game), location, method, cond)
}

pub(crate) fn get_wild_pokemon_from_entries(
    entries: &[RawEntry],
    location: &str,
    method: Method,
    cond: &Conditions,
) -> Vec<ResolvedEncounter> {
    let entry = match entries.iter().find(|e| e.location == location) {
        Some(e) => e,
        None => return vec![],
    };

    match method {
        Method::Grass => resolve_grass(entry, cond),
        Method::Surf => resolve_water(entry.surf, &WATER_SLOT_RATES, entry, false),
        Method::OldRod => resolve_water(entry.old_rod, &WATER_SLOT_RATES, entry, cond.feebas_tile),
        Method::GoodRod => {
            resolve_water(entry.good_rod, &WATER_SLOT_RATES, entry, cond.feebas_tile)
        }
        Method::SuperRod => {
            resolve_water(entry.super_rod, &WATER_SLOT_RATES, entry, cond.feebas_tile)
        }
    }
}

fn resolve_grass(entry: &RawEntry, cond: &Conditions) -> Vec<ResolvedEncounter> {
    let mut species: Vec<&'static str> = entry.grass.iter().map(|s| s.species).collect();
    let levels: Vec<u8> = entry.grass.iter().map(|s| s.level).collect();

    if cond.swarm_active {
        set_slot(&mut species, 0, entry.swarm.first().copied());
        set_slot(&mut species, 1, entry.swarm.get(1).copied());
    }

    if let Some(tod) = cond.time_of_day {
        let arr = match tod {
            TimeOfDay::Day => entry.day,
            TimeOfDay::Night => entry.night,
        };
        set_slot(&mut species, 2, arr.first().copied());
        set_slot(&mut species, 3, arr.get(1).copied());
    }

    if cond.radar_active {
        set_slot(&mut species, 4, entry.radar.first().copied());
        set_slot(&mut species, 5, entry.radar.get(1).copied());
        set_slot(&mut species, 10, entry.radar.get(2).copied());
        set_slot(&mut species, 11, entry.radar.get(3).copied());
    }

    if let Some(cart) = cond.dual_slot {
        let arr: &[&'static str] = match cart {
            DualSlotCartridge::Ruby => entry.dual_slot.ruby,
            DualSlotCartridge::Sapphire => entry.dual_slot.sapphire,
            DualSlotCartridge::Emerald => entry.dual_slot.emerald,
            DualSlotCartridge::FireRed => entry.dual_slot.firered,
            DualSlotCartridge::LeafGreen => entry.dual_slot.leafgreen,
        };
        set_slot(&mut species, 8, arr.first().copied());
        set_slot(&mut species, 9, arr.get(1).copied());
    }

    species
        .iter()
        .zip(levels.iter())
        .zip(GRASS_SLOT_RATES.iter())
        .enumerate()
        .filter(|(_, ((sp, _), _))| !sp.is_empty())
        .map(|(i, ((sp, lvl), rate))| ResolvedEncounter {
            species: sp,
            form: shellos_gastrodon_form(sp, entry),
            min_level: *lvl,
            max_level: *lvl,
            rate_percent: *rate,
            slot: i,
        })
        .collect()
}

fn resolve_water(
    slots: &[RawWaterSlot],
    rates: &[u32; 5],
    entry: &RawEntry,
    feebas_tile: bool,
) -> Vec<ResolvedEncounter> {
    let mut out: Vec<ResolvedEncounter> = slots
        .iter()
        .zip(rates.iter())
        .enumerate()
        .filter(|(_, (s, _))| !s.species.is_empty())
        .map(|(i, (s, rate))| ResolvedEncounter {
            species: s.species,
            form: shellos_gastrodon_form(s.species, entry),
            min_level: s.min_level,
            max_level: s.max_level,
            rate_percent: *rate,
            slot: i,
        })
        .collect();

    if feebas_tile && entry.location == MT_CORONET_B1F_LOCATION {
        out.push(ResolvedEncounter {
            species: FEEBAS_SPECIES,
            form: 0,
            min_level: FEEBAS_MIN_LEVEL,
            max_level: FEEBAS_MAX_LEVEL,
            rate_percent: FEEBAS_RATE_PERCENT_WHEN_TILE,
            slot: 5,
        });
    }

    out
}

fn shellos_gastrodon_form(species: &str, entry: &RawEntry) -> u8 {
    if species == SHELLOS_SPECIES {
        if entry.form.first().copied().unwrap_or(0) == 0 {
            1
        } else {
            0
        }
    } else if species == GASTRODON_SPECIES {
        if entry.form.get(1).copied().unwrap_or(0) == 0 {
            1
        } else {
            0
        }
    } else {
        0
    }
}

fn set_slot(species: &mut [&'static str], idx: usize, value: Option<&'static str>) {
    if let (Some(v), Some(slot)) = (value, species.get_mut(idx)) {
        if !v.is_empty() {
            *slot = v;
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HoneyGroup {
    Normal,
    Rare,
    Munchlax,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HoneyResolvedEncounter {
    pub species: &'static str,
    pub min_level: u8,
    pub max_level: u8,
    pub group: HoneyGroup,
    pub slot: usize,
}

fn tree_id_from_location(location: &str) -> Option<u8> {
    HONEY_TREE_MAP_IDS
        .iter()
        .position(|&id| id == location)
        .map(|i| i as u8)
}

pub fn get_honey_tree_pokemon(
    game: Game,
    location: &str,
    tid: u16,
    sid: u16,
) -> Vec<HoneyResolvedEncounter> {
    get_honey_tree_pokemon_from_entries(honey_for(game), location, tid, sid)
}

pub(crate) fn get_honey_tree_pokemon_from_entries(
    entries: &[RawHoneyEntry],
    location: &str,
    tid: u16,
    sid: u16,
) -> Vec<HoneyResolvedEncounter> {
    let entry = match entries.iter().find(|e| e.location == location) {
        Some(e) => e,
        None => return vec![],
    };

    let munchlax_available = match tree_id_from_location(location) {
        Some(tree_id) => get_muchlax_trees(tid, sid).contains(&HoneyTreeLocation::from(tree_id)),
        None => false,
    };

    let mut seen: Vec<&'static str> = Vec::new();
    let mut out = Vec::new();

    let mut push_group = |slots: &[RawWaterSlot], group: HoneyGroup| {
        for (i, s) in slots.iter().enumerate() {
            if s.species.is_empty() || seen.contains(&s.species) {
                continue;
            }
            seen.push(s.species);
            out.push(HoneyResolvedEncounter {
                species: s.species,
                min_level: s.min_level,
                max_level: s.max_level,
                group,
                slot: i,
            });
        }
    };

    push_group(entry.normal, HoneyGroup::Normal);
    push_group(entry.rare, HoneyGroup::Rare);
    if munchlax_available {
        push_group(entry.munchlax, HoneyGroup::Munchlax);
    }

    out
}

pub fn merge_by_species(mut list: Vec<ResolvedEncounter>) -> Vec<ResolvedEncounter> {
    list.sort_by_key(|e| (e.species, e.form));
    let mut out: Vec<ResolvedEncounter> = Vec::new();
    for enc in list {
        if let Some(last) = out.last_mut() {
            if last.species == enc.species && last.form == enc.form {
                last.rate_percent += enc.rate_percent;
                last.min_level = last.min_level.min(enc.min_level);
                last.max_level = last.max_level.max(enc.max_level);
                continue;
            }
        }
        out.push(enc);
    }
    out
}

// Example usage:
//
// let cond = Conditions {
//     time_of_day: Some(TimeOfDay::Night),
//     swarm_active: false,
//     radar_active: false,
//     dual_slot: None,
//     feebas_tile: false,
// };
//
// let results = get_wild_pokemon(Game::Platinum, "Route 205", Method::Grass, &cond);
// for r in merge_by_species(results) {
//     println!(
//         "{} (form {}) lv{}-{} ({}%) [slot {}]",
//         r.species, r.form, r.min_level, r.max_level, r.rate_percent, r.slot
//     );
// }
//
// for r in get_honey_tree_pokemon(Game::Platinum, "Route 205", profile_tid, profile_sid) {
//     println!("{:?} {} lv{}-{}", r.group, r.species, r.min_level, r.max_level);
// }

#[cfg(test)]
mod tests {
    use super::*;

    fn location_0() -> RawEntry {
        RawEntry {
            location: "Canalave City",
            rates: RawRates {
                grass: 0,
                surf: 10,
                old_rod: 25,
                good_rod: 50,
                super_rod: 75,
            },
            grass: &[RawGrassSlot {
                species: "",
                level: 0,
            }; 12],
            swarm: &["", ""],
            day: &["", ""],
            night: &["", ""],
            radar: &["", "", "", ""],
            form: &[0, 0],
            dual_slot: RawDualSlot {
                ruby: &["", ""],
                sapphire: &["", ""],
                emerald: &["", ""],
                firered: &["", ""],
                leafgreen: &["", ""],
            },
            surf: &[
                RawWaterSlot {
                    species: "Tentacool",
                    min_level: 20,
                    max_level: 30,
                },
                RawWaterSlot {
                    species: "Shellos",
                    min_level: 20,
                    max_level: 30,
                },
                RawWaterSlot {
                    species: "Tentacruel",
                    min_level: 20,
                    max_level: 40,
                },
                RawWaterSlot {
                    species: "Tentacruel",
                    min_level: 20,
                    max_level: 40,
                },
                RawWaterSlot {
                    species: "Gastrodon",
                    min_level: 20,
                    max_level: 40,
                },
            ],
            old_rod: &[
                RawWaterSlot {
                    species: "Magikarp",
                    min_level: 4,
                    max_level: 6,
                },
                RawWaterSlot {
                    species: "Magikarp",
                    min_level: 3,
                    max_level: 7,
                },
                RawWaterSlot {
                    species: "Magikarp",
                    min_level: 5,
                    max_level: 10,
                },
                RawWaterSlot {
                    species: "Magikarp",
                    min_level: 5,
                    max_level: 10,
                },
                RawWaterSlot {
                    species: "Magikarp",
                    min_level: 5,
                    max_level: 15,
                },
            ],
            good_rod: &[
                RawWaterSlot {
                    species: "Magikarp",
                    min_level: 15,
                    max_level: 20,
                },
                RawWaterSlot {
                    species: "Finneon",
                    min_level: 15,
                    max_level: 20,
                },
                RawWaterSlot {
                    species: "Magikarp",
                    min_level: 10,
                    max_level: 25,
                },
                RawWaterSlot {
                    species: "Finneon",
                    min_level: 10,
                    max_level: 25,
                },
                RawWaterSlot {
                    species: "Finneon",
                    min_level: 10,
                    max_level: 25,
                },
            ],
            super_rod: &[
                RawWaterSlot {
                    species: "Gyarados",
                    min_level: 30,
                    max_level: 55,
                },
                RawWaterSlot {
                    species: "Lumineon",
                    min_level: 30,
                    max_level: 40,
                },
                RawWaterSlot {
                    species: "Staryu",
                    min_level: 20,
                    max_level: 50,
                },
                RawWaterSlot {
                    species: "Lumineon",
                    min_level: 40,
                    max_level: 55,
                },
                RawWaterSlot {
                    species: "Lumineon",
                    min_level: 40,
                    max_level: 55,
                },
            ],
        }
    }

    fn location_synth() -> RawEntry {
        RawEntry {
            location: "TestZone",
            rates: RawRates {
                grass: 20,
                surf: 0,
                old_rod: 0,
                good_rod: 0,
                super_rod: 0,
            },
            grass: &[
                RawGrassSlot {
                    species: "Sp1",
                    level: 10,
                },
                RawGrassSlot {
                    species: "Sp2",
                    level: 10,
                },
                RawGrassSlot {
                    species: "Sp3",
                    level: 11,
                },
                RawGrassSlot {
                    species: "Sp4",
                    level: 11,
                },
                RawGrassSlot {
                    species: "Sp5",
                    level: 12,
                },
                RawGrassSlot {
                    species: "Sp6",
                    level: 12,
                },
                RawGrassSlot {
                    species: "Sp7",
                    level: 13,
                },
                RawGrassSlot {
                    species: "Sp8",
                    level: 13,
                },
                RawGrassSlot {
                    species: "Sp9",
                    level: 14,
                },
                RawGrassSlot {
                    species: "Sp10",
                    level: 14,
                },
                RawGrassSlot {
                    species: "Sp11",
                    level: 15,
                },
                RawGrassSlot {
                    species: "Sp12",
                    level: 15,
                },
            ],
            swarm: &["SwarmA", "SwarmB"],
            day: &["DayA", "DayB"],
            night: &["NightA", "NightB"],
            radar: &["RadarA", "RadarB", "RadarC", "RadarD"],
            form: &[0, 0],
            dual_slot: RawDualSlot {
                ruby: &["RubyA", "RubyB"],
                sapphire: &["", ""],
                emerald: &["", ""],
                firered: &["", ""],
                leafgreen: &["", ""],
            },
            surf: &[],
            old_rod: &[],
            good_rod: &[],
            super_rod: &[],
        }
    }

    /// Entry for Mt Coronet Upper B1F, to test Feebas.
    fn location_22() -> RawEntry {
        RawEntry {
            location: "Mt Coronet Upper B1F",
            rates: RawRates {
                grass: 0,
                surf: 0,
                old_rod: 30,
                good_rod: 30,
                super_rod: 30,
            },
            grass: &[RawGrassSlot {
                species: "",
                level: 0,
            }; 12],
            swarm: &["", ""],
            day: &["", ""],
            night: &["", ""],
            radar: &["", "", "", ""],
            form: &[0, 0],
            dual_slot: RawDualSlot {
                ruby: &["", ""],
                sapphire: &["", ""],
                emerald: &["", ""],
                firered: &["", ""],
                leafgreen: &["", ""],
            },
            surf: &[],
            old_rod: &[
                RawWaterSlot {
                    species: "Magikarp",
                    min_level: 10,
                    max_level: 20,
                },
                RawWaterSlot {
                    species: "Magikarp",
                    min_level: 10,
                    max_level: 20,
                },
                RawWaterSlot {
                    species: "Magikarp",
                    min_level: 10,
                    max_level: 20,
                },
                RawWaterSlot {
                    species: "Magikarp",
                    min_level: 10,
                    max_level: 20,
                },
                RawWaterSlot {
                    species: "Magikarp",
                    min_level: 10,
                    max_level: 20,
                },
            ],
            good_rod: &[],
            super_rod: &[],
        }
    }

    fn honey_145() -> RawHoneyEntry {
        RawHoneyEntry {
            location: "Route 205 (South)",
            normal: &[
                RawWaterSlot {
                    species: "Combee",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Wurmple",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Burmy",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Cherubi",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Aipom",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Aipom",
                    min_level: 5,
                    max_level: 15,
                },
            ],
            rare: &[
                RawWaterSlot {
                    species: "Burmy",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Cherubi",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Combee",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Aipom",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Aipom",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Heracross",
                    min_level: 5,
                    max_level: 15,
                },
            ],
            munchlax: &[
                RawWaterSlot {
                    species: "Munchlax",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Munchlax",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Munchlax",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Munchlax",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Munchlax",
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: "Munchlax",
                    min_level: 5,
                    max_level: 15,
                },
            ],
        }
    }

    fn honey_entry_at_unknown_location() -> RawHoneyEntry {
        let mut e = honey_145();
        e.location = "UnknownHoneyLocation";
        e
    }

    #[test]
    fn parses_location_0_from_real_sample() {
        let entry = location_0();
        assert_eq!(entry.location, "Canalave City");
        assert_eq!(entry.grass.len(), 12);
        assert_eq!(entry.surf.len(), 5);
        assert_eq!(entry.old_rod[0].species, "Magikarp");
    }

    #[test]
    fn grass_all_zero_species_returns_empty() {
        let entries = [location_0()];
        let result = get_wild_pokemon_from_entries(
            &entries,
            "Canalave City",
            Method::Grass,
            &Conditions::default(),
        );
        assert!(result.is_empty());
    }

    #[test]
    fn grass_base_slots_no_conditions() {
        let entries = [location_synth()];
        let result = get_wild_pokemon_from_entries(
            &entries,
            "TestZone",
            Method::Grass,
            &Conditions::default(),
        );
        assert_eq!(result.len(), 12);
        let species: Vec<&str> = result.iter().map(|e| e.species).collect();
        assert_eq!(
            species,
            vec![
                "Sp1", "Sp2", "Sp3", "Sp4", "Sp5", "Sp6", "Sp7", "Sp8", "Sp9", "Sp10", "Sp11",
                "Sp12"
            ]
        );
        assert_eq!(result[0].rate_percent, 20);
        assert_eq!(result[0].min_level, 10);
        assert_eq!(result[0].max_level, 10);
    }

    #[test]
    fn grass_swarm_overrides_only_slots_0_and_1() {
        let entries = [location_synth()];
        let cond = Conditions {
            swarm_active: true,
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, "TestZone", Method::Grass, &cond);
        let species: Vec<&str> = result.iter().map(|e| e.species).collect();
        assert_eq!(
            species,
            vec![
                "SwarmA", "SwarmB", "Sp3", "Sp4", "Sp5", "Sp6", "Sp7", "Sp8", "Sp9", "Sp10",
                "Sp11", "Sp12"
            ]
        );
    }

    #[test]
    fn grass_day_overrides_only_slots_2_and_3() {
        let entries = [location_synth()];
        let cond = Conditions {
            time_of_day: Some(TimeOfDay::Day),
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, "TestZone", Method::Grass, &cond);
        let species: Vec<&str> = result.iter().map(|e| e.species).collect();
        assert_eq!(
            species,
            vec![
                "Sp1", "Sp2", "DayA", "DayB", "Sp5", "Sp6", "Sp7", "Sp8", "Sp9", "Sp10", "Sp11",
                "Sp12"
            ]
        );
    }

    #[test]
    fn grass_night_overrides_only_slots_2_and_3() {
        let entries = [location_synth()];
        let cond = Conditions {
            time_of_day: Some(TimeOfDay::Night),
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, "TestZone", Method::Grass, &cond);
        let species: Vec<&str> = result.iter().map(|e| e.species).collect();
        assert_eq!(
            species,
            vec![
                "Sp1", "Sp2", "NightA", "NightB", "Sp5", "Sp6", "Sp7", "Sp8", "Sp9", "Sp10",
                "Sp11", "Sp12"
            ]
        );
    }

    #[test]
    fn grass_radar_overrides_slots_4_5_10_11_not_contiguous() {
        let entries = [location_synth()];
        let cond = Conditions {
            radar_active: true,
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, "TestZone", Method::Grass, &cond);
        let species: Vec<&str> = result.iter().map(|e| e.species).collect();
        assert_eq!(
            species,
            vec![
                "Sp1", "Sp2", "Sp3", "Sp4", "RadarA", "RadarB", "Sp7", "Sp8", "Sp9", "Sp10",
                "RadarC", "RadarD"
            ]
        );
    }

    #[test]
    fn grass_dual_slot_overrides_only_slots_8_and_9() {
        let entries = [location_synth()];
        let cond = Conditions {
            dual_slot: Some(DualSlotCartridge::Ruby),
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, "TestZone", Method::Grass, &cond);
        let species: Vec<&str> = result.iter().map(|e| e.species).collect();
        assert_eq!(
            species,
            vec![
                "Sp1", "Sp2", "Sp3", "Sp4", "Sp5", "Sp6", "Sp7", "Sp8", "RubyA", "RubyB", "Sp11",
                "Sp12"
            ]
        );
    }

    #[test]
    fn grass_dual_slot_other_cartridge_is_empty_so_no_override() {
        let entries = [location_synth()];
        let cond = Conditions {
            dual_slot: Some(DualSlotCartridge::Sapphire),
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, "TestZone", Method::Grass, &cond);
        let species: Vec<&str> = result.iter().map(|e| e.species).collect();
        assert_eq!(
            species,
            vec![
                "Sp1", "Sp2", "Sp3", "Sp4", "Sp5", "Sp6", "Sp7", "Sp8", "Sp9", "Sp10", "Sp11",
                "Sp12"
            ]
        );
    }

    #[test]
    fn grass_multiple_conditions_are_disjoint_and_all_apply() {
        let entries = [location_synth()];
        let cond = Conditions {
            swarm_active: true,
            time_of_day: Some(TimeOfDay::Day),
            radar_active: true,
            dual_slot: Some(DualSlotCartridge::Ruby),
            feebas_tile: false,
        };
        let result = get_wild_pokemon_from_entries(&entries, "TestZone", Method::Grass, &cond);
        let species: Vec<&str> = result.iter().map(|e| e.species).collect();
        assert_eq!(
            species,
            vec![
                "SwarmA", "SwarmB", "DayA", "DayB", "RadarA", "RadarB", "Sp7", "Sp8", "RubyA",
                "RubyB", "RadarC", "RadarD"
            ]
        );
    }

    #[test]
    fn surf_returns_correct_species_levels_and_rates_in_slot_order() {
        let entries = [location_0()];
        let result = get_wild_pokemon_from_entries(
            &entries,
            "Canalave City",
            Method::Surf,
            &Conditions::default(),
        );
        assert_eq!(result.len(), 5);
        let expected_species = [
            "Tentacool",
            "Shellos",
            "Tentacruel",
            "Tentacruel",
            "Gastrodon",
        ];
        let expected_rates = [60, 30, 5, 4, 1];
        for (i, enc) in result.iter().enumerate() {
            assert_eq!(enc.species, expected_species[i], "slot {i}");
            assert_eq!(enc.rate_percent, expected_rates[i], "slot {i}");
            assert_eq!(enc.slot, i);
        }
        assert_eq!(result[0].min_level, 20);
        assert_eq!(result[0].max_level, 30);
    }

    #[test]
    fn surf_shellos_and_gastrodon_get_west_form_when_flags_are_zero() {
        let entries = [location_0()];
        let result = get_wild_pokemon_from_entries(
            &entries,
            "Canalave City",
            Method::Surf,
            &Conditions::default(),
        );
        let shellos = result
            .iter()
            .find(|e| e.species == SHELLOS_SPECIES)
            .unwrap();
        let gastrodon = result
            .iter()
            .find(|e| e.species == GASTRODON_SPECIES)
            .unwrap();
        assert_eq!(shellos.form, 1);
        assert_eq!(gastrodon.form, 1);
    }

    #[test]
    fn old_rod_returns_correct_species_and_level_ranges() {
        let entries = [location_0()];
        let result = get_wild_pokemon_from_entries(
            &entries,
            "Canalave City",
            Method::OldRod,
            &Conditions::default(),
        );
        assert_eq!(result.len(), 5);
        assert!(result.iter().all(|e| e.species == "Magikarp"));
        assert_eq!(result[0].min_level, 4);
        assert_eq!(result[0].max_level, 6);
        assert_eq!(result[4].min_level, 5);
        assert_eq!(result[4].max_level, 15);
    }

    #[test]
    fn good_rod_returns_mixed_species() {
        let entries = [location_0()];
        let result = get_wild_pokemon_from_entries(
            &entries,
            "Canalave City",
            Method::GoodRod,
            &Conditions::default(),
        );
        let species: Vec<&str> = result.iter().map(|e| e.species).collect();
        assert_eq!(
            species,
            vec!["Magikarp", "Finneon", "Magikarp", "Finneon", "Finneon"]
        );
    }

    #[test]
    fn super_rod_returns_correct_species() {
        let entries = [location_0()];
        let result = get_wild_pokemon_from_entries(
            &entries,
            "Canalave City",
            Method::SuperRod,
            &Conditions::default(),
        );
        let species: Vec<&str> = result.iter().map(|e| e.species).collect();
        assert_eq!(
            species,
            vec!["Gyarados", "Lumineon", "Staryu", "Lumineon", "Lumineon"]
        );
    }

    #[test]
    fn feebas_tile_replaces_slot_5_at_mt_coronet_b1f() {
        let entries = [location_22()];
        let cond = Conditions {
            feebas_tile: true,
            ..Default::default()
        };
        let result =
            get_wild_pokemon_from_entries(&entries, "Mt Coronet Upper B1F", Method::OldRod, &cond);
        assert_eq!(result.len(), 6);
        let feebas = result.iter().find(|e| e.slot == 5).unwrap();
        assert_eq!(feebas.species, FEEBAS_SPECIES);
        assert_eq!(feebas.min_level, FEEBAS_MIN_LEVEL);
        assert_eq!(feebas.max_level, FEEBAS_MAX_LEVEL);
        assert_eq!(feebas.rate_percent, FEEBAS_RATE_PERCENT_WHEN_TILE);
        assert!(
            result
                .iter()
                .filter(|e| e.slot != 5)
                .all(|e| e.species == "Magikarp")
        );
        assert_eq!(result.iter().filter(|e| e.slot != 5).count(), 5);
    }

    #[test]
    fn feebas_tile_false_does_not_replace_anything() {
        let entries = [location_22()];
        let result = get_wild_pokemon_from_entries(
            &entries,
            "Mt Coronet Upper B1F",
            Method::OldRod,
            &Conditions::default(),
        );
        assert!(result.iter().all(|e| e.species == "Magikarp"));
    }

    #[test]
    fn feebas_tile_true_but_wrong_location_does_not_replace() {
        let entries = [location_0()];
        let cond = Conditions {
            feebas_tile: true,
            ..Default::default()
        };
        let result =
            get_wild_pokemon_from_entries(&entries, "Canalave City", Method::OldRod, &cond);
        assert!(result.iter().all(|e| e.species == "Magikarp"));
        assert!(!result.iter().any(|e| e.species == FEEBAS_SPECIES));
    }

    #[test]
    fn honey_tree_dedups_species_across_normal_and_rare() {
        let entries = [honey_145()];
        let munchlax_trees = get_muchlax_trees(0, 0);
        assert!(munchlax_trees.contains(&HoneyTreeLocation::from(0u8)));
        let result = get_honey_tree_pokemon_from_entries(&entries, "Route 205 (South)", 0, 0);
        let species: Vec<&str> = result.iter().map(|e| e.species).collect();
        assert_eq!(
            species,
            vec![
                "Combee",
                "Wurmple",
                "Burmy",
                "Cherubi",
                "Aipom",
                "Heracross",
                "Munchlax"
            ]
        );
        let groups: Vec<HoneyGroup> = result.iter().map(|e| e.group).collect();
        assert_eq!(
            groups,
            vec![
                HoneyGroup::Normal,
                HoneyGroup::Normal,
                HoneyGroup::Normal,
                HoneyGroup::Normal,
                HoneyGroup::Normal,
                HoneyGroup::Rare,
                HoneyGroup::Munchlax,
            ]
        );
    }

    #[test]
    fn honey_tree_without_valid_tree_id_never_includes_munchlax() {
        let entries = [honey_entry_at_unknown_location()];
        let result = get_honey_tree_pokemon_from_entries(&entries, "UnknownHoneyLocation", 0, 0);
        assert!(!result.iter().any(|e| e.group == HoneyGroup::Munchlax));
        assert!(!result.iter().any(|e| e.species == "Munchlax"));
    }

    #[test]
    fn honey_tree_unknown_location_returns_empty() {
        let entries: [RawHoneyEntry; 0] = [];
        let result = get_honey_tree_pokemon_from_entries(&entries, "Route 205 (South)", 0, 0);
        assert!(result.is_empty());
    }

    #[test]
    fn tree_id_from_location_matches_known_list() {
        assert_eq!(tree_id_from_location("Route 205 (South)"), Some(0));
        assert_eq!(tree_id_from_location("Floaroma Meadow"), Some(20));
        assert_eq!(tree_id_from_location("does-not-exist"), None);
    }

    #[test]
    fn merge_by_species_sums_rates_and_widens_level_range() {
        let list = vec![
            ResolvedEncounter {
                species: "Magikarp",
                form: 0,
                min_level: 5,
                max_level: 10,
                rate_percent: 20,
                slot: 0,
            },
            ResolvedEncounter {
                species: "Magikarp",
                form: 0,
                min_level: 3,
                max_level: 8,
                rate_percent: 10,
                slot: 4,
            },
            ResolvedEncounter {
                species: "Gyarados",
                form: 0,
                min_level: 20,
                max_level: 20,
                rate_percent: 1,
                slot: 11,
            },
        ];
        let merged = merge_by_species(list);
        assert_eq!(merged.len(), 2);
        let m_karp = merged.iter().find(|e| e.species == "Magikarp").unwrap();
        assert_eq!(m_karp.rate_percent, 30);
        assert_eq!(m_karp.min_level, 3);
        assert_eq!(m_karp.max_level, 10);
    }
}
