//! Runtime data structures used by the tool.
//!
//! These types don't implement `Deserialize` and don't use `Vec`. Instead,
//! they store data in `&'static [T]`, allowing them to be embedded directly
//! into the binary as static values. This avoids any memory allocation or
//! JSON parsing when the tool starts.
//!
//! The actual data is generated by `src/bin/generate_wild4.rs`. That generator
//! reads the original JSON only once during development/build time and produces
//! `src/gen4/generated_wild4.rs`, which contains the fully initialized static
//! data used at runtime.
//!
//! The encounter resolution logic (`resolve_grass`, `resolve_water`, etc.)
//! remains exactly the same as before. It still depends on `Conditions`, which
//! are only available at runtime (active swarms, time of day, radar state,
//! and so on), so this logic can't be precomputed by the generator. What the
//! generator removes is the JSON parsing and struct conversion step, while the
//! game logic itself stays unchanged.

use crate::gen4::generated_wild4;
use crate::gen4::honey_tree::{HoneyTreeLocation, get_muchlax_trees};

#[derive(Debug, Clone, Copy)]
pub struct RawEntry {
    pub location: u32,
    pub rates: RawRates,
    pub grass: &'static [RawGrassSlot],
    pub swarm: &'static [u16],
    pub day: &'static [u16],
    pub night: &'static [u16],
    pub radar: &'static [u16],
    pub form: &'static [u8],
    pub dual_slot: RawDualSlot,
    pub surf: &'static [RawWaterSlot],
    pub old_rod: &'static [RawWaterSlot],
    pub good_rod: &'static [RawWaterSlot],
    pub super_rod: &'static [RawWaterSlot],
}

#[derive(Debug, Clone, Copy)]
pub struct RawRates {
    pub grass: u32,
    pub surf: u32,
    pub old_rod: u32,
    pub good_rod: u32,
    pub super_rod: u32,
}

#[derive(Debug, Clone, Copy)]
pub struct RawGrassSlot {
    pub species: u16,
    pub level: u8,
}

#[derive(Debug, Clone, Copy)]
pub struct RawWaterSlot {
    pub species: u16,
    pub min_level: u8,
    pub max_level: u8,
}

#[derive(Debug, Clone, Copy)]
pub struct RawDualSlot {
    pub ruby: &'static [u16],
    pub sapphire: &'static [u16],
    pub emerald: &'static [u16],
    pub firered: &'static [u16],
    pub leafgreen: &'static [u16],
}

#[derive(Debug, Clone, Copy)]
pub struct RawHoneyEntry {
    pub location: u32,
    pub normal: &'static [RawWaterSlot],
    pub rare: &'static [RawWaterSlot],
    pub munchlax: &'static [RawWaterSlot],
}

const GRASS_SLOT_RATES: [u32; 12] = [20, 20, 10, 10, 10, 10, 5, 5, 4, 4, 1, 1];
const WATER_SLOT_RATES: [u32; 5] = [60, 30, 5, 4, 1];

const MT_CORONET_B1F_LOCATION: u32 = 22;
const FEEBAS_SPECIES: u16 = 349;
const FEEBAS_MIN_LEVEL: u8 = 10;
const FEEBAS_MAX_LEVEL: u8 = 20;

const SHELLOS_SPECIES: u16 = 422;
const GASTRODON_SPECIES: u16 = 423;

const FEEBAS_RATE_PERCENT_WHEN_TILE: u32 = 50;

const HONEY_TREE_MAP_IDS: [u32; 21] = [
    145, 146, 147, 148, 149, 150, 156, 157, 159, 160, 161, 162, 163, 164, 167, 169, 170, 7, 8, 9,
    183,
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Game {
    Diamond,
    Pearl,
    Platinum,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Method {
    Grass,
    Surf,
    OldRod,
    GoodRod,
    SuperRod,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TimeOfDay {
    Day,
    Night,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DualSlotCartridge {
    Ruby,
    Sapphire,
    Emerald,
    FireRed,
    LeafGreen,
}

#[derive(Debug, Clone, Default)]
pub struct Conditions {
    pub time_of_day: Option<TimeOfDay>,
    pub swarm_active: bool,
    pub radar_active: bool,
    pub dual_slot: Option<DualSlotCartridge>,
    pub feebas_tile: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResolvedEncounter {
    pub species: u16,
    pub form: u8,
    pub min_level: u8,
    pub max_level: u8,
    pub rate_percent: u32,
    pub slot: usize,
}

fn encounters_for(game: Game) -> &'static [RawEntry] {
    match game {
        Game::Diamond => generated_wild4::DIAMOND_ENTRIES,
        Game::Pearl => generated_wild4::PEARL_ENTRIES,
        Game::Platinum => generated_wild4::PLATINUM_ENTRIES,
    }
}

fn honey_for(game: Game) -> &'static [RawHoneyEntry] {
    match game {
        Game::Diamond => generated_wild4::DIAMOND_HONEY,
        Game::Pearl => generated_wild4::PEARL_HONEY,
        Game::Platinum => generated_wild4::PLATINUM_HONEY,
    }
}

pub fn get_wild_pokemon(
    game: Game,
    location: u32,
    method: Method,
    cond: &Conditions,
) -> Vec<ResolvedEncounter> {
    get_wild_pokemon_from_entries(encounters_for(game), location, method, cond)
}

pub(crate) fn get_wild_pokemon_from_entries(
    entries: &[RawEntry],
    location: u32,
    method: Method,
    cond: &Conditions,
) -> Vec<ResolvedEncounter> {
    let entry = match entries.iter().find(|e| e.location == location) {
        Some(e) => e,
        None => return vec![],
    };

    match method {
        Method::Grass => resolve_grass(entry, cond),
        Method::Surf => resolve_water(entry.surf, &WATER_SLOT_RATES, entry, false),
        Method::OldRod => resolve_water(entry.old_rod, &WATER_SLOT_RATES, entry, cond.feebas_tile),
        Method::GoodRod => {
            resolve_water(entry.good_rod, &WATER_SLOT_RATES, entry, cond.feebas_tile)
        }
        Method::SuperRod => {
            resolve_water(entry.super_rod, &WATER_SLOT_RATES, entry, cond.feebas_tile)
        }
    }
}

fn resolve_grass(entry: &RawEntry, cond: &Conditions) -> Vec<ResolvedEncounter> {
    let mut species: Vec<u16> = entry.grass.iter().map(|s| s.species).collect();
    let levels: Vec<u8> = entry.grass.iter().map(|s| s.level).collect();

    if cond.swarm_active {
        set_slot(&mut species, 0, entry.swarm.first().copied());
        set_slot(&mut species, 1, entry.swarm.get(1).copied());
    }

    if let Some(tod) = cond.time_of_day {
        let arr = match tod {
            TimeOfDay::Day => entry.day,
            TimeOfDay::Night => entry.night,
        };
        set_slot(&mut species, 2, arr.first().copied());
        set_slot(&mut species, 3, arr.get(1).copied());
    }

    if cond.radar_active {
        set_slot(&mut species, 4, entry.radar.first().copied());
        set_slot(&mut species, 5, entry.radar.get(1).copied());
        set_slot(&mut species, 10, entry.radar.get(2).copied());
        set_slot(&mut species, 11, entry.radar.get(3).copied());
    }

    if let Some(cart) = cond.dual_slot {
        let arr: &[u16] = match cart {
            DualSlotCartridge::Ruby => entry.dual_slot.ruby,
            DualSlotCartridge::Sapphire => entry.dual_slot.sapphire,
            DualSlotCartridge::Emerald => entry.dual_slot.emerald,
            DualSlotCartridge::FireRed => entry.dual_slot.firered,
            DualSlotCartridge::LeafGreen => entry.dual_slot.leafgreen,
        };
        set_slot(&mut species, 8, arr.first().copied());
        set_slot(&mut species, 9, arr.get(1).copied());
    }

    species
        .iter()
        .zip(levels.iter())
        .zip(GRASS_SLOT_RATES.iter())
        .enumerate()
        .filter(|(_, ((sp, _), _))| **sp != 0)
        .map(|(i, ((sp, lvl), rate))| ResolvedEncounter {
            species: *sp,
            form: shellos_gastrodon_form(*sp, entry),
            min_level: *lvl,
            max_level: *lvl,
            rate_percent: *rate,
            slot: i,
        })
        .collect()
}

fn resolve_water(
    slots: &[RawWaterSlot],
    rates: &[u32; 5],
    entry: &RawEntry,
    feebas_tile: bool,
) -> Vec<ResolvedEncounter> {
    let mut out: Vec<ResolvedEncounter> = slots
        .iter()
        .zip(rates.iter())
        .enumerate()
        .filter(|(_, (s, _))| s.species != 0)
        .map(|(i, (s, rate))| ResolvedEncounter {
            species: s.species,
            form: shellos_gastrodon_form(s.species, entry),
            min_level: s.min_level,
            max_level: s.max_level,
            rate_percent: *rate,
            slot: i,
        })
        .collect();

    if feebas_tile && entry.location == MT_CORONET_B1F_LOCATION {
        out.push(ResolvedEncounter {
            species: FEEBAS_SPECIES,
            form: 0,
            min_level: FEEBAS_MIN_LEVEL,
            max_level: FEEBAS_MAX_LEVEL,
            rate_percent: FEEBAS_RATE_PERCENT_WHEN_TILE,
            slot: 5,
        });
    }

    out
}

fn shellos_gastrodon_form(species: u16, entry: &RawEntry) -> u8 {
    if species == SHELLOS_SPECIES {
        if entry.form.first().copied().unwrap_or(0) == 0 {
            1
        } else {
            0
        }
    } else if species == GASTRODON_SPECIES {
        if entry.form.get(1).copied().unwrap_or(0) == 0 {
            1
        } else {
            0
        }
    } else {
        0
    }
}

fn set_slot(species: &mut [u16], idx: usize, value: Option<u16>) {
    if let (Some(v), Some(slot)) = (value, species.get_mut(idx)) {
        if v != 0 {
            *slot = v;
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HoneyGroup {
    Normal,
    Rare,
    Munchlax,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HoneyResolvedEncounter {
    pub species: u16,
    pub min_level: u8,
    pub max_level: u8,
    pub group: HoneyGroup,
    pub slot: usize,
}

fn tree_id_from_location(location: u32) -> Option<u8> {
    HONEY_TREE_MAP_IDS
        .iter()
        .position(|&id| id == location)
        .map(|i| i as u8)
}

pub fn get_honey_tree_pokemon(
    game: Game,
    location: u32,
    tid: u16,
    sid: u16,
) -> Vec<HoneyResolvedEncounter> {
    get_honey_tree_pokemon_from_entries(honey_for(game), location, tid, sid)
}

pub(crate) fn get_honey_tree_pokemon_from_entries(
    entries: &[RawHoneyEntry],
    location: u32,
    tid: u16,
    sid: u16,
) -> Vec<HoneyResolvedEncounter> {
    let entry = match entries.iter().find(|e| e.location == location) {
        Some(e) => e,
        None => return vec![],
    };

    let munchlax_available = match tree_id_from_location(location) {
        Some(tree_id) => get_muchlax_trees(tid, sid).contains(&HoneyTreeLocation::from(tree_id)),
        None => false,
    };

    let mut seen: Vec<u16> = Vec::new();
    let mut out = Vec::new();

    let mut push_group = |slots: &[RawWaterSlot], group: HoneyGroup| {
        for (i, s) in slots.iter().enumerate() {
            if s.species == 0 || seen.contains(&s.species) {
                continue;
            }
            seen.push(s.species);
            out.push(HoneyResolvedEncounter {
                species: s.species,
                min_level: s.min_level,
                max_level: s.max_level,
                group,
                slot: i,
            });
        }
    };

    push_group(entry.normal, HoneyGroup::Normal);
    push_group(entry.rare, HoneyGroup::Rare);
    if munchlax_available {
        push_group(entry.munchlax, HoneyGroup::Munchlax);
    }

    out
}

pub fn merge_by_species(mut list: Vec<ResolvedEncounter>) -> Vec<ResolvedEncounter> {
    list.sort_by_key(|e| (e.species, e.form));
    let mut out: Vec<ResolvedEncounter> = Vec::new();
    for enc in list {
        if let Some(last) = out.last_mut() {
            if last.species == enc.species && last.form == enc.form {
                last.rate_percent += enc.rate_percent;
                last.min_level = last.min_level.min(enc.min_level);
                last.max_level = last.max_level.max(enc.max_level);
                continue;
            }
        }
        out.push(enc);
    }
    out
}

// Example usage:
//
// let cond = Conditions {
//     time_of_day: Some(TimeOfDay::Night),
//     swarm_active: false,
//     radar_active: false,
//     dual_slot: None,
//     feebas_tile: false,
// };
//
// let results = get_wild_pokemon(Game::Platinum, location, Method::Grass, &cond);
// for r in merge_by_species(results) {
//     println!(
//         "species#{} (form {}) lv{}-{} ({}%) [slot {}]",
//         r.species, r.form, r.min_level, r.max_level, r.rate_percent, r.slot
//     );
// }
//
// for r in get_honey_tree_pokemon(Game::Platinum, 145, profile_tid, profile_sid) {
//     println!("{:?} species#{} lv{}-{}", r.group, r.species, r.min_level, r.max_level);
// }

#[cfg(test)]
mod tests {
    use super::*;

    fn location_0() -> RawEntry {
        RawEntry {
            location: 0,
            rates: RawRates {
                grass: 0,
                surf: 10,
                old_rod: 25,
                good_rod: 50,
                super_rod: 75,
            },
            grass: &[RawGrassSlot {
                species: 0,
                level: 0,
            }; 12],
            swarm: &[0, 0],
            day: &[0, 0],
            night: &[0, 0],
            radar: &[0, 0, 0, 0],
            form: &[0, 0],
            dual_slot: RawDualSlot {
                ruby: &[0, 0],
                sapphire: &[0, 0],
                emerald: &[0, 0],
                firered: &[0, 0],
                leafgreen: &[0, 0],
            },
            surf: &[
                RawWaterSlot {
                    species: 72,
                    min_level: 20,
                    max_level: 30,
                },
                RawWaterSlot {
                    species: 422,
                    min_level: 20,
                    max_level: 30,
                },
                RawWaterSlot {
                    species: 73,
                    min_level: 20,
                    max_level: 40,
                },
                RawWaterSlot {
                    species: 73,
                    min_level: 20,
                    max_level: 40,
                },
                RawWaterSlot {
                    species: 423,
                    min_level: 20,
                    max_level: 40,
                },
            ],
            old_rod: &[
                RawWaterSlot {
                    species: 129,
                    min_level: 4,
                    max_level: 6,
                },
                RawWaterSlot {
                    species: 129,
                    min_level: 3,
                    max_level: 7,
                },
                RawWaterSlot {
                    species: 129,
                    min_level: 5,
                    max_level: 10,
                },
                RawWaterSlot {
                    species: 129,
                    min_level: 5,
                    max_level: 10,
                },
                RawWaterSlot {
                    species: 129,
                    min_level: 5,
                    max_level: 15,
                },
            ],
            good_rod: &[
                RawWaterSlot {
                    species: 129,
                    min_level: 15,
                    max_level: 20,
                },
                RawWaterSlot {
                    species: 456,
                    min_level: 15,
                    max_level: 20,
                },
                RawWaterSlot {
                    species: 129,
                    min_level: 10,
                    max_level: 25,
                },
                RawWaterSlot {
                    species: 456,
                    min_level: 10,
                    max_level: 25,
                },
                RawWaterSlot {
                    species: 456,
                    min_level: 10,
                    max_level: 25,
                },
            ],
            super_rod: &[
                RawWaterSlot {
                    species: 130,
                    min_level: 30,
                    max_level: 55,
                },
                RawWaterSlot {
                    species: 457,
                    min_level: 30,
                    max_level: 40,
                },
                RawWaterSlot {
                    species: 120,
                    min_level: 20,
                    max_level: 50,
                },
                RawWaterSlot {
                    species: 457,
                    min_level: 40,
                    max_level: 55,
                },
                RawWaterSlot {
                    species: 457,
                    min_level: 40,
                    max_level: 55,
                },
            ],
        }
    }

    fn location_synth() -> RawEntry {
        RawEntry {
            location: 999,
            rates: RawRates {
                grass: 20,
                surf: 0,
                old_rod: 0,
                good_rod: 0,
                super_rod: 0,
            },
            grass: &[
                RawGrassSlot {
                    species: 1,
                    level: 10,
                },
                RawGrassSlot {
                    species: 2,
                    level: 10,
                },
                RawGrassSlot {
                    species: 3,
                    level: 11,
                },
                RawGrassSlot {
                    species: 4,
                    level: 11,
                },
                RawGrassSlot {
                    species: 5,
                    level: 12,
                },
                RawGrassSlot {
                    species: 6,
                    level: 12,
                },
                RawGrassSlot {
                    species: 7,
                    level: 13,
                },
                RawGrassSlot {
                    species: 8,
                    level: 13,
                },
                RawGrassSlot {
                    species: 9,
                    level: 14,
                },
                RawGrassSlot {
                    species: 10,
                    level: 14,
                },
                RawGrassSlot {
                    species: 11,
                    level: 15,
                },
                RawGrassSlot {
                    species: 12,
                    level: 15,
                },
            ],
            swarm: &[100, 101],
            day: &[200, 201],
            night: &[300, 301],
            radar: &[400, 401, 402, 403],
            form: &[0, 0],
            dual_slot: RawDualSlot {
                ruby: &[500, 501],
                sapphire: &[0, 0],
                emerald: &[0, 0],
                firered: &[0, 0],
                leafgreen: &[0, 0],
            },
            surf: &[],
            old_rod: &[],
            good_rod: &[],
            super_rod: &[],
        }
    }

    /// Entry for location 22 (Mt Coronet Upper B1F), to test Feebas.
    fn location_22() -> RawEntry {
        RawEntry {
            location: 22,
            rates: RawRates {
                grass: 0,
                surf: 0,
                old_rod: 30,
                good_rod: 30,
                super_rod: 30,
            },
            grass: &[RawGrassSlot {
                species: 0,
                level: 0,
            }; 12],
            swarm: &[0, 0],
            day: &[0, 0],
            night: &[0, 0],
            radar: &[0, 0, 0, 0],
            form: &[0, 0],
            dual_slot: RawDualSlot {
                ruby: &[0, 0],
                sapphire: &[0, 0],
                emerald: &[0, 0],
                firered: &[0, 0],
                leafgreen: &[0, 0],
            },
            surf: &[],
            old_rod: &[
                RawWaterSlot {
                    species: 129,
                    min_level: 10,
                    max_level: 20,
                },
                RawWaterSlot {
                    species: 129,
                    min_level: 10,
                    max_level: 20,
                },
                RawWaterSlot {
                    species: 129,
                    min_level: 10,
                    max_level: 20,
                },
                RawWaterSlot {
                    species: 129,
                    min_level: 10,
                    max_level: 20,
                },
                RawWaterSlot {
                    species: 129,
                    min_level: 10,
                    max_level: 20,
                },
            ],
            good_rod: &[],
            super_rod: &[],
        }
    }

    fn honey_145() -> RawHoneyEntry {
        RawHoneyEntry {
            location: 145,
            normal: &[
                RawWaterSlot {
                    species: 415,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 265,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 412,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 420,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 190,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 190,
                    min_level: 5,
                    max_level: 15,
                },
            ],
            rare: &[
                RawWaterSlot {
                    species: 412,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 420,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 415,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 190,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 190,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 214,
                    min_level: 5,
                    max_level: 15,
                },
            ],
            munchlax: &[
                RawWaterSlot {
                    species: 446,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 446,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 446,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 446,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 446,
                    min_level: 5,
                    max_level: 15,
                },
                RawWaterSlot {
                    species: 446,
                    min_level: 5,
                    max_level: 15,
                },
            ],
        }
    }

    fn honey_entry_at_unknown_location() -> RawHoneyEntry {
        let mut e = honey_145();
        e.location = 9999;
        e
    }

    #[test]
    fn parses_location_0_from_real_sample() {
        let entry = location_0();
        assert_eq!(entry.location, 0);
        assert_eq!(entry.grass.len(), 12);
        assert_eq!(entry.surf.len(), 5);
        assert_eq!(entry.old_rod[0].species, 129);
    }

    #[test]
    fn grass_all_zero_species_returns_empty() {
        let entries = [location_0()];
        let result =
            get_wild_pokemon_from_entries(&entries, 0, Method::Grass, &Conditions::default());
        assert!(result.is_empty());
    }

    #[test]
    fn grass_base_slots_no_conditions() {
        let entries = [location_synth()];
        let result =
            get_wild_pokemon_from_entries(&entries, 999, Method::Grass, &Conditions::default());
        assert_eq!(result.len(), 12);
        let species: Vec<u16> = result.iter().map(|e| e.species).collect();
        assert_eq!(species, vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]);
        assert_eq!(result[0].rate_percent, 20);
        assert_eq!(result[0].min_level, 10);
        assert_eq!(result[0].max_level, 10);
    }

    #[test]
    fn grass_swarm_overrides_only_slots_0_and_1() {
        let entries = [location_synth()];
        let cond = Conditions {
            swarm_active: true,
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, 999, Method::Grass, &cond);
        let species: Vec<u16> = result.iter().map(|e| e.species).collect();
        assert_eq!(species, vec![100, 101, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]);
    }

    #[test]
    fn grass_day_overrides_only_slots_2_and_3() {
        let entries = [location_synth()];
        let cond = Conditions {
            time_of_day: Some(TimeOfDay::Day),
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, 999, Method::Grass, &cond);
        let species: Vec<u16> = result.iter().map(|e| e.species).collect();
        assert_eq!(species, vec![1, 2, 200, 201, 5, 6, 7, 8, 9, 10, 11, 12]);
    }

    #[test]
    fn grass_night_overrides_only_slots_2_and_3() {
        let entries = [location_synth()];
        let cond = Conditions {
            time_of_day: Some(TimeOfDay::Night),
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, 999, Method::Grass, &cond);
        let species: Vec<u16> = result.iter().map(|e| e.species).collect();
        assert_eq!(species, vec![1, 2, 300, 301, 5, 6, 7, 8, 9, 10, 11, 12]);
    }

    #[test]
    fn grass_radar_overrides_slots_4_5_10_11_not_contiguous() {
        let entries = [location_synth()];
        let cond = Conditions {
            radar_active: true,
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, 999, Method::Grass, &cond);
        let species: Vec<u16> = result.iter().map(|e| e.species).collect();
        assert_eq!(species, vec![1, 2, 3, 4, 400, 401, 7, 8, 9, 10, 402, 403]);
    }

    #[test]
    fn grass_dual_slot_overrides_only_slots_8_and_9() {
        let entries = [location_synth()];
        let cond = Conditions {
            dual_slot: Some(DualSlotCartridge::Ruby),
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, 999, Method::Grass, &cond);
        let species: Vec<u16> = result.iter().map(|e| e.species).collect();
        assert_eq!(species, vec![1, 2, 3, 4, 5, 6, 7, 8, 500, 501, 11, 12]);
    }

    #[test]
    fn grass_dual_slot_other_cartridge_is_zero_so_no_override() {
        let entries = [location_synth()];
        let cond = Conditions {
            dual_slot: Some(DualSlotCartridge::Sapphire),
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, 999, Method::Grass, &cond);
        let species: Vec<u16> = result.iter().map(|e| e.species).collect();
        assert_eq!(species, vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]);
    }

    #[test]
    fn grass_multiple_conditions_are_disjoint_and_all_apply() {
        let entries = [location_synth()];
        let cond = Conditions {
            swarm_active: true,
            time_of_day: Some(TimeOfDay::Day),
            radar_active: true,
            dual_slot: Some(DualSlotCartridge::Ruby),
            feebas_tile: false,
        };
        let result = get_wild_pokemon_from_entries(&entries, 999, Method::Grass, &cond);
        let species: Vec<u16> = result.iter().map(|e| e.species).collect();
        assert_eq!(
            species,
            vec![100, 101, 200, 201, 400, 401, 7, 8, 500, 501, 402, 403]
        );
    }

    #[test]
    fn surf_returns_correct_species_levels_and_rates_in_slot_order() {
        let entries = [location_0()];
        let result =
            get_wild_pokemon_from_entries(&entries, 0, Method::Surf, &Conditions::default());
        assert_eq!(result.len(), 5);
        let expected_species = [72, 422, 73, 73, 423];
        let expected_rates = [60, 30, 5, 4, 1];
        for (i, enc) in result.iter().enumerate() {
            assert_eq!(enc.species, expected_species[i], "slot {i}");
            assert_eq!(enc.rate_percent, expected_rates[i], "slot {i}");
            assert_eq!(enc.slot, i);
        }
        assert_eq!(result[0].min_level, 20);
        assert_eq!(result[0].max_level, 30);
    }

    #[test]
    fn surf_shellos_and_gastrodon_get_west_form_when_flags_are_zero() {
        let entries = [location_0()];
        let result =
            get_wild_pokemon_from_entries(&entries, 0, Method::Surf, &Conditions::default());
        let shellos = result
            .iter()
            .find(|e| e.species == SHELLOS_SPECIES)
            .unwrap();
        let gastrodon = result
            .iter()
            .find(|e| e.species == GASTRODON_SPECIES)
            .unwrap();
        assert_eq!(shellos.form, 1);
        assert_eq!(gastrodon.form, 1);
    }

    #[test]
    fn old_rod_returns_correct_species_and_level_ranges() {
        let entries = [location_0()];
        let result =
            get_wild_pokemon_from_entries(&entries, 0, Method::OldRod, &Conditions::default());
        assert_eq!(result.len(), 5);
        assert!(result.iter().all(|e| e.species == 129));
        assert_eq!(result[0].min_level, 4);
        assert_eq!(result[0].max_level, 6);
        assert_eq!(result[4].min_level, 5);
        assert_eq!(result[4].max_level, 15);
    }

    #[test]
    fn good_rod_returns_mixed_species() {
        let entries = [location_0()];
        let result =
            get_wild_pokemon_from_entries(&entries, 0, Method::GoodRod, &Conditions::default());
        let species: Vec<u16> = result.iter().map(|e| e.species).collect();
        assert_eq!(species, vec![129, 456, 129, 456, 456]);
    }

    #[test]
    fn super_rod_returns_correct_species() {
        let entries = [location_0()];
        let result =
            get_wild_pokemon_from_entries(&entries, 0, Method::SuperRod, &Conditions::default());
        let species: Vec<u16> = result.iter().map(|e| e.species).collect();
        assert_eq!(species, vec![130, 457, 120, 457, 457]);
    }

    #[test]
    fn feebas_tile_replaces_slot_5_at_mt_coronet_b1f() {
        let entries = [location_22()];
        let cond = Conditions {
            feebas_tile: true,
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, 22, Method::OldRod, &cond);
        assert_eq!(result.len(), 6);
        let feebas = result.iter().find(|e| e.slot == 5).unwrap();
        assert_eq!(feebas.species, FEEBAS_SPECIES);
        assert_eq!(feebas.min_level, FEEBAS_MIN_LEVEL);
        assert_eq!(feebas.max_level, FEEBAS_MAX_LEVEL);
        assert_eq!(feebas.rate_percent, FEEBAS_RATE_PERCENT_WHEN_TILE);
        assert!(
            result
                .iter()
                .filter(|e| e.slot != 5)
                .all(|e| e.species == 129)
        );
        assert_eq!(result.iter().filter(|e| e.slot != 5).count(), 5);
    }

    #[test]
    fn feebas_tile_false_does_not_replace_anything() {
        let entries = [location_22()];
        let result =
            get_wild_pokemon_from_entries(&entries, 22, Method::OldRod, &Conditions::default());
        assert!(result.iter().all(|e| e.species == 129));
    }

    #[test]
    fn feebas_tile_true_but_wrong_location_does_not_replace() {
        let entries = [location_0()];
        let cond = Conditions {
            feebas_tile: true,
            ..Default::default()
        };
        let result = get_wild_pokemon_from_entries(&entries, 0, Method::OldRod, &cond);
        assert!(result.iter().all(|e| e.species == 129));
        assert!(!result.iter().any(|e| e.species == FEEBAS_SPECIES));
    }

    #[test]
    fn honey_tree_dedups_species_across_normal_and_rare() {
        let entries = [honey_145()];
        let munchlax_trees = get_muchlax_trees(0, 0);
        assert!(munchlax_trees.contains(&HoneyTreeLocation::from(0u8)));
        let result = get_honey_tree_pokemon_from_entries(&entries, 145, 0, 0);
        let species: Vec<u16> = result.iter().map(|e| e.species).collect();
        assert_eq!(species, vec![415, 265, 412, 420, 190, 214, 446]);
        let groups: Vec<HoneyGroup> = result.iter().map(|e| e.group).collect();
        assert_eq!(
            groups,
            vec![
                HoneyGroup::Normal,
                HoneyGroup::Normal,
                HoneyGroup::Normal,
                HoneyGroup::Normal,
                HoneyGroup::Normal,
                HoneyGroup::Rare,
                HoneyGroup::Munchlax,
            ]
        );
    }

    #[test]
    fn honey_tree_without_valid_tree_id_never_includes_munchlax() {
        let entries = [honey_entry_at_unknown_location()]; // location 9999
        let result = get_honey_tree_pokemon_from_entries(&entries, 9999, 0, 0);
        assert!(!result.iter().any(|e| e.group == HoneyGroup::Munchlax));
        assert!(!result.iter().any(|e| e.species == 446));
    }

    #[test]
    fn honey_tree_unknown_location_returns_empty() {
        let entries: [RawHoneyEntry; 0] = [];
        let result = get_honey_tree_pokemon_from_entries(&entries, 145, 0, 0);
        assert!(result.is_empty());
    }

    #[test]
    fn tree_id_from_location_matches_known_list() {
        assert_eq!(tree_id_from_location(145), Some(0));
        assert_eq!(tree_id_from_location(183), Some(20));
        assert_eq!(tree_id_from_location(9999), None);
    }

    #[test]
    fn merge_by_species_sums_rates_and_widens_level_range() {
        let list = vec![
            ResolvedEncounter {
                species: 129,
                form: 0,
                min_level: 5,
                max_level: 10,
                rate_percent: 20,
                slot: 0,
            },
            ResolvedEncounter {
                species: 129,
                form: 0,
                min_level: 3,
                max_level: 8,
                rate_percent: 10,
                slot: 4,
            },
            ResolvedEncounter {
                species: 130,
                form: 0,
                min_level: 20,
                max_level: 20,
                rate_percent: 1,
                slot: 11,
            },
        ];
        let merged = merge_by_species(list);
        assert_eq!(merged.len(), 2);
        let m129 = merged.iter().find(|e| e.species == 129).unwrap();
        assert_eq!(m129.rate_percent, 30);
        assert_eq!(m129.min_level, 3);
        assert_eq!(m129.max_level, 10);
    }
}
