import { CycleAtMoment } from "~/rngTools";
import {
  Field,
  ResultColumn,
  FormFieldTable,
  ResultTable,
  Switch,
} from "~/components";
import React from "react";
import { z } from "zod";
import { TextArea } from "~/components/textArea";
import { ExternalLink } from "~/components/link";

type UiResultCycleAtMoment = CycleAtMoment & {
  uid: number;
  increment: number;
  diff_cycle_with_compare: number | null;
  diff_increment_with_compare: number | null;
};

const uiCycleAtMomentColumns: ResultColumn<UiResultCycleAtMoment>[] = [
  {
    title: "Moment",
    dataIndex: "moment",
  },
  {
    title: (
      <>
        Cycle from
        <br />
        Sweet Scent start
      </>
    ),
    dataIndex: "cycle",
    key: "cycle",
    render: (cycle, values) => {
      if (values.diff_cycle_with_compare === null) {
        return `${cycle}`;
      }

      const sign = values.diff_cycle_with_compare > 0 ? "+" : "";
      return `${cycle} (${sign}${values.diff_cycle_with_compare})`;
    },
  },
  {
    title: "Increment",
    dataIndex: "increment",
    render: (increment, values) => {
      if (values.diff_increment_with_compare === null) {
        return `${increment}`;
      }

      const sign = values.diff_increment_with_compare > 0 ? "+" : "";
      return `${increment} (${sign}${values.diff_increment_with_compare})`;
    },
  },
];

const compareCycleAtMomentsSchema = z.object({
  advanceAtSweetScentWildEncounter: z.number().optional(),
  cycleAtSweetScentWildEncounter: z.number().optional(),
  cycleAtMoments: z.array(
    z.object({
      moment: z.string(),
      cycle: z.number(),
    }),
  ),
});

const parseCompareCycleAtMoments = (input: string) => {
  try {
    const info = JSON.parse(input);
    return compareCycleAtMomentsSchema.parse(info);
  } catch {
    return null;
  }
};

type Props = {
  cycleAtMoments: CycleAtMoment[];
};

export const Wild3CycleAtMoments = ({ cycleAtMoments }: Props) => {
  const [compareCycleAtMomentsStr, setCompareCycleAtMomentsStr] =
    React.useState("");

  const [displayDebuggingOptions, setDisplayDebuggingOptions] =
    React.useState(false);

  const uiResultsCycleAtMoment = React.useMemo(() => {
    const compareCycleAtMoments = parseCompareCycleAtMoments(
      compareCycleAtMomentsStr,
    );
    return cycleAtMoments.map((cycleAtMoment, idx) => {
      const prevInfo = idx === 0 ? undefined : cycleAtMoments[idx - 1];
      const compareInfo = compareCycleAtMoments?.cycleAtMoments.find(
        (cac) => cac.moment === cycleAtMoment.moment,
      );
      const comparePrevCycle =
        idx === 0
          ? 0
          : compareCycleAtMoments?.cycleAtMoments.find(
              (cac) => cac.moment === prevInfo?.moment,
            )?.cycle;

      const increment = cycleAtMoment.cycle - (prevInfo?.cycle ?? 0);

      if (compareInfo != null && comparePrevCycle != null) {
        const compareIncrement = compareInfo.cycle - comparePrevCycle;
        const diff_increment_with_compare = increment - compareIncrement;
        return {
          ...cycleAtMoment,
          uid: Math.random(),
          diff_cycle_with_compare: cycleAtMoment.cycle - compareInfo.cycle,
          increment,
          diff_increment_with_compare,
        };
      }
      return {
        ...cycleAtMoment,
        uid: Math.random(),
        increment,
        diff_cycle_with_compare: null,
        diff_increment_with_compare: null,
      };
    });
  }, [cycleAtMoments, compareCycleAtMomentsStr]);

  const fields: Field[] = React.useMemo(() => {
    return [
      {
        label: "Display debugging options?",
        input: (
          <Switch
            onChange={(val) => {
              setDisplayDebuggingOptions(val);
            }}
          />
        ),
      },
      ...(displayDebuggingOptions
        ? [
            {
              label: (
                <>
                  Copy-paste the JSON generated by this{" "}
                  <a href="https://raw.githubusercontent.com/RainingChain/pk_emu_scripts/refs/heads/main/Gen3/wild3_cycle_at_moments.lua">
                    lua script
                  </a>{" "}
                  after a wild encounter to compare with the tool results.
                </>
              ),
              key: "compareCycleAtMomentsStr",
              direction: "column" as const,
              input: (
                <TextArea
                  rows={5}
                  onChange={(val) => {
                    setCompareCycleAtMomentsStr(val.target.value);
                  }}
                />
              ),
            },
          ]
        : []),
    ];
  }, [displayDebuggingOptions]);

  return (
    <>
      <FormFieldTable fields={fields} />
      {displayDebuggingOptions && (
        <div>
          <strong>Use case:</strong> Detect when the tool miscalculates cycles
          and simplify its calibration by developpers.
        </div>
      )}
      {displayDebuggingOptions && (
        <ResultTable<UiResultCycleAtMoment>
          columns={uiCycleAtMomentColumns}
          rowKey="uid"
          dataSource={uiResultsCycleAtMoment}
        />
      )}
    </>
  );
};
