import { CycleAtMoment, Gen3Method, rngTools } from "~/rngTools";
import {
  Field,
  ResultColumn,
  FormFieldTable,
  ResultTable,
  Switch,
  Flex,
  Typography,
} from "~/components";
import React from "react";
import { z } from "zod";
import { TextArea } from "~/components/textArea";
import { formatLargeInteger } from "~/utils/formatLargeInteger";
import { gen3Methods } from "~/types";

const VBLANK_FREQ = 280_896;
const MOST_PROBABLE_CYCLE_AT_SWEET_SCENT = 55_000;
const MOST_PROBABLE_VBLANK_CYCLE = 60_000;

type UiResult = {
  methodFromJson: Gen3Method | null;
  methodFromTool: Gen3Method | null;
  cycleAtSweetScent: number;
  frameAtSweetScent: number;
  advanceAtSweetScent: number;
  uiCycleAtMoments: UiResultCycleAtMoment[];
  vblankDurations: number[];
  errorMsg: string;
};

type UiResultCycleAtMoment = {
  uid: number;
  moment: string;
  dataFromJson: {
    cycle: number;
    frame: number;
    cycleFromSweetScent: number;
    cycleFromSweetScentIncrement: number;
  };
  dataFromTool: {
    cycle: number;
    frame: number;
    cycleFromSweetScent: number;
    cycleFromSweetScentIncrement: number;
  };
  dataDiff: {
    cycleFromSweetScent: number;
    cycleFromSweetScentIncrement: number;
  };
};

const uiCycleAtMomentColumns: ResultColumn<UiResultCycleAtMoment>[] = [
  {
    title: "Moment",
    dataIndex: "moment",
  },
  {
    type: "group",
    title: "Data predicted by Webtool",
    columns: [
      {
        title: "Frame",
        key: "dataFromTool_Frame",
        dataIndex: "dataFromTool",
        render: (dataFromTool) => {
          return formatLargeInteger(dataFromTool.frame);
        },
      },
      {
        title: "Cycle",
        key: "dataFromTool_Cycle",
        dataIndex: "dataFromTool",
        render: (dataFromTool) => {
          return formatLargeInteger(dataFromTool.cycle);
        },
      },
      {
        title: (
          <>
            Cycle from
            <br />
            Sweet Scent start
            <br />
            excluding Vblank
          </>
        ),
        key: "dataFromJson_CycleSweetScent",
        dataIndex: "dataFromTool",
        render: (dataFromTool) => {
          return formatLargeInteger(dataFromTool.cycleFromSweetScent);
        },
      },
      {
        title: "Increment",
        key: "dataFromJson_Increment",
        dataIndex: "dataFromTool",
        render: (dataFromTool) => {
          return `+${formatLargeInteger(dataFromTool.cycleFromSweetScentIncrement)}`;
        },
      },
    ],
  },
  {
    type: "group",
    title: "Data from JSON generated by emulator (lua)",
    columns: [
      {
        title: "Frame",
        key: "dataFromJson_Frame",
        dataIndex: "dataFromJson",
        render: (dataFromJson) => {
          return formatLargeInteger(dataFromJson.frame);
        },
      },
      {
        title: "Cycle",
        key: "dataFromJson_Cycle",
        dataIndex: "dataFromJson",
        render: (dataFromJson) => {
          return formatLargeInteger(dataFromJson.cycle);
        },
      },
      {
        title: (
          <>
            Cycle from
            <br />
            Sweet Scent start
            <br />
            excluding Vblank
          </>
        ),
        key: "dataFromJson_CycleSweetScent",
        dataIndex: "dataFromJson",
        render: (dataFromJson) => {
          return formatLargeInteger(dataFromJson.cycleFromSweetScent);
        },
      },
      {
        title: "Increment",
        key: "dataFromJson_Increment",
        dataIndex: "dataFromJson",
        render: (dataFromJson) => {
          return `+${formatLargeInteger(dataFromJson.cycleFromSweetScentIncrement)}`;
        },
      },
    ],
  },
  {
    type: "group",
    title: "Webtool difference with JSON",
    columns: [
      {
        title: (
          <>
            Cycle from
            <br />
            Sweet Scent start
            <br />
            excluding Vblank
          </>
        ),
        key: "dataDiff_CycleSweetScent",
        dataIndex: "dataDiff",
        render: (dataDiff) => {
          return formatLargeInteger(dataDiff.cycleFromSweetScent);
        },
      },
      {
        title: "Increment",
        key: "dataDiff_Increment",
        dataIndex: "dataDiff",
        render: (dataDiff) => {
          const prefix = dataDiff.cycleFromSweetScentIncrement >= 0 ? "+" : "";
          return `${prefix}${formatLargeInteger(dataDiff.cycleFromSweetScentIncrement)}`;
        },
      },
    ],
  },
  {
    // Repeat the column so it also appears next to the Difference columns, to help compare.
    title: "Moment",
    key: "Moment2",
    dataIndex: "moment",
  },
];

const cycleAtMomentsFromJsonSchema = z.object({
  version: z.string(),
  cycleAtMoments: z.array(
    z.object({
      moment: z.string(),
      cycle: z.number(),
      frame: z.number(),
      adv: z.number(),
    }),
  ),
  leadPID: z.string(),
  advance: z.number(),
  method: z.enum(gen3Methods),
});

export type CycleAtMomentsJson = z.infer<typeof cycleAtMomentsFromJsonSchema>;

const parseCycleAtMomentsJsonStr = (input: string) => {
  try {
    const info = JSON.parse(input);
    return cycleAtMomentsFromJsonSchema.parse(info);
  } catch {
    return null;
  }
};

type Props = {
  cycleAtMomentsFromTool: CycleAtMoment[];
  /** leadCycleSpeedFromTool is null if egg lead */
  leadCycleSpeed: number | null;
  advanceAtSweetScent: number;
};

let nextUid = 0;

const createEmptyUiResult = (
  json: CycleAtMomentsJson | null,
  cycleAtMomentsFromToolForFallback: CycleAtMoment[],
): UiResult => {
  const moments =
    json == null
      ? cycleAtMomentsFromToolForFallback.map((cam) => cam.moment)
      : json.cycleAtMoments
          .filter((cam) => cam.moment !== "VblankIntr_End")
          .map((cam) => cam.moment);

  const uiCycleAtMoments: UiResultCycleAtMoment[] = moments.map((moment) => {
    return {
      uid: nextUid++,
      moment,
      dataFromJson: {
        cycle: 0,
        frame: 0,
        cycleFromSweetScent: 0,
        cycleFromSweetScentIncrement: 0,
      },
      dataFromTool: {
        cycle: 0,
        frame: 0,
        cycleFromSweetScent: 0,
        cycleFromSweetScentIncrement: 0,
      },
      dataDiff: {
        cycleFromSweetScent: 0,
        cycleFromSweetScentIncrement: 0,
      },
    };
  });

  return {
    methodFromJson: null,
    methodFromTool: null,
    cycleAtSweetScent: 0,
    frameAtSweetScent: 0,
    advanceAtSweetScent: 0,
    uiCycleAtMoments,
    vblankDurations: [],
    errorMsg: "",
  };
};

const createUiResult = async (
  compareCycleAtMomentsStr: string,
  cycleAtMomentsFromTool: CycleAtMoment[],
  leadCycleSpeedFromTool: number | null,
  advanceAtSweetScent: number,
) => {
  const json = parseCycleAtMomentsJsonStr(compareCycleAtMomentsStr);
  const uiResult = createEmptyUiResult(json, cycleAtMomentsFromTool);

  if (compareCycleAtMomentsStr !== "" && json == null) {
    uiResult.errorMsg = "Error: Invalid JSON format or content.";
  }

  if (json != null) {
    fillDataFromJson(uiResult, json);

    if (uiResult.advanceAtSweetScent !== advanceAtSweetScent) {
      uiResult.errorMsg = `Error: The advance used in the emulator ${uiResult.advanceAtSweetScent} doesn't match the advance provided on the webtool ${advanceAtSweetScent}.`;
    }

    if (leadCycleSpeedFromTool !== null) {
      const leadPIDFromJson = parseInt(json.leadPID, 16);

      const leadCycleSpeedFromJson = isNaN(leadPIDFromJson)
        ? 0
        : await rngTools.calculate_pid_speed(leadPIDFromJson);

      if (leadCycleSpeedFromJson !== leadCycleSpeedFromTool) {
        uiResult.errorMsg =
          "Error: The lead used in the emulator doesn't match the lead provided on the webtool.";
      }
    }
  }

  fillDataFromTool(uiResult, cycleAtMomentsFromTool);
  calculateDataDiff(uiResult);

  return uiResult;
};

const fillDataFromTool = (
  uiResult: UiResult,
  cycleAtMomentsFromTool: CycleAtMoment[],
) => {
  if (uiResult.cycleAtSweetScent === 0) {
    // No JSON was loaded.
    uiResult.cycleAtSweetScent = MOST_PROBABLE_CYCLE_AT_SWEET_SCENT; // Most probable cycle at Sweet Scent
  }

  const { uiCycleAtMoments } = uiResult;
  uiCycleAtMoments.forEach((uiCam, i) => {
    const camFromTool = cycleAtMomentsFromTool.find(
      (cam) => cam.moment === uiCam.moment,
    );
    if (camFromTool == null) {
      if (i !== 0) {
        uiCam.dataFromTool.cycleFromSweetScent =
          uiCycleAtMoments[i - 1].dataFromTool.cycleFromSweetScent; // assume 0 increment.
      }
    } else {
      uiCam.dataFromTool.cycleFromSweetScent = camFromTool.cycle;
      if (i !== 0) {
        uiCam.dataFromTool.cycleFromSweetScentIncrement =
          uiCam.dataFromTool.cycleFromSweetScent -
          uiCycleAtMoments[i - 1].dataFromTool.cycleFromSweetScent;
      }
    }

    const totalCycle =
      uiCam.dataFromTool.cycleFromSweetScent + uiResult.cycleAtSweetScent;
    let cycleAfterVblank = totalCycle;
    let vblankCount = 0;
    while (cycleAfterVblank > VBLANK_FREQ) {
      const vblankDur =
        uiResult.vblankDurations[vblankCount] ?? MOST_PROBABLE_VBLANK_CYCLE;
      cycleAfterVblank = cycleAfterVblank - VBLANK_FREQ + vblankDur;
      vblankCount++;
    }

    uiCam.dataFromTool.cycle = cycleAfterVblank;
    uiCam.dataFromTool.frame = uiResult.frameAtSweetScent + vblankCount;
  });

  uiResult.methodFromTool = getMethodAccordingToTool(uiResult);
};

const fillDataFromJson = (uiResult: UiResult, json: CycleAtMomentsJson) => {
  /* 
  Example:
    json has [
      {"moment":"SweetScentWildEncounter",        "cycle":54797, "frame":2026},
      {"moment":"ChooseWildMonIndex_Land_Random", "cycle":94959, "frame":2026},
      {"moment":"VblankIntr_End",                 "cycle":50235, "frame":2027},
      {"moment":"CreateBoxMon_RandomIvs1",        "cycle":60589, "frame":2027},
      {"moment":"CreateBoxMon_RandomIvs2",        "cycle":102544, "frame":2027},
    ]
    
    uiResults.dataFromData will become: [
     {"moment":"SweetScentWildEncounter",        "cycleFromSweetScent":54797}
     {"moment":"ChooseWildMonIndex_Land_Random", "cycleFromSweetScent":94959}
     {"moment":"CreateBoxMon_RandomIvs1",        "cycleFromSweetScent":60589 + (280896 - 50235)}
     {"moment":"CreateBoxMon_RandomIvs2",        "cycleFromSweetScent":102544 + (280896 - 50235)}
   ]
  */

  uiResult.methodFromJson = json.method;

  uiResult.vblankDurations = json.cycleAtMoments
    .filter((cam) => {
      return cam.moment === "VblankIntr_End";
    })
    .map((cam) => cam.cycle);

  const { uiCycleAtMoments } = uiResult;

  json.cycleAtMoments.forEach((cam) => {
    if (cam.moment === "VblankIntr_End") {
      return;
    }

    const uiResultIdx = uiCycleAtMoments.findIndex(
      (uiRes) => uiRes.moment === cam.moment,
    );
    if (uiResultIdx === -1) {
      return;
    }

    const previousVblanksIncr = json.cycleAtMoments
      .filter((vblank) => {
        return vblank.moment === "VblankIntr_End" && vblank.frame <= cam.frame;
      })
      .map((vblank) => {
        return VBLANK_FREQ - vblank.cycle;
      })
      .reduce((prev, cur) => prev + cur, 0);

    const { dataFromJson } = uiCycleAtMoments[uiResultIdx];
    dataFromJson.cycle = cam.cycle;
    dataFromJson.frame = cam.frame;
    dataFromJson.cycleFromSweetScent =
      uiResultIdx == 0
        ? 0
        : cam.cycle +
          previousVblanksIncr -
          uiCycleAtMoments[0].dataFromJson.cycle;

    if (uiResultIdx !== 0) {
      dataFromJson.cycleFromSweetScentIncrement =
        dataFromJson.cycleFromSweetScent -
        uiCycleAtMoments[uiResultIdx - 1].dataFromJson.cycleFromSweetScent;
    }
  });

  const firstCam = uiResult.uiCycleAtMoments[0];
  if (firstCam != null) {
    uiResult.cycleAtSweetScent = firstCam.dataFromJson.cycle;
    uiResult.frameAtSweetScent = firstCam.dataFromJson.frame;
    uiResult.advanceAtSweetScent = json.cycleAtMoments[0].adv;
  }
};

const calculateDataDiff = (uiResult: UiResult) => {
  uiResult.uiCycleAtMoments.forEach((uiCam) => {
    uiCam.dataDiff.cycleFromSweetScent =
      uiCam.dataFromTool.cycleFromSweetScent -
      uiCam.dataFromJson.cycleFromSweetScent;

    uiCam.dataDiff.cycleFromSweetScentIncrement =
      uiCam.dataFromTool.cycleFromSweetScentIncrement -
      uiCam.dataFromJson.cycleFromSweetScentIncrement;
  });
};

const getMethodAccordingToTool = (uiResult: UiResult): Gen3Method | null => {
  let method: Gen3Method = "Wild5";
  for (const cam of uiResult.uiCycleAtMoments) {
    if (cam.dataFromTool.frame !== uiResult.frameAtSweetScent) {
      // first VBlank
      return method;
    }
    if (cam.moment == "CreateMonWithNature_RandomPidLowLast") {
      method = "Wild3";
    }
    if (cam.moment == "CreateMonWithNature_RandomPidHighLast") {
      method = "Wild2";
    }
    if (cam.moment == "CreateBoxMon_RandomIvs1") {
      method = "Wild4";
    }
  }

  return "Wild1";
};

export const Wild3CycleAtMoments = ({
  cycleAtMomentsFromTool,
  leadCycleSpeed,
  advanceAtSweetScent,
}: Props) => {
  cycleAtMomentsFromTool = [
    { moment: "SweetScentWildEncounter", cycle: 0 },
    ...cycleAtMomentsFromTool,
  ];
  const [compareCycleAtMomentsStr, setCompareCycleAtMomentsStr] =
    React.useState("");

  const [displayDebuggingOptions, setDisplayDebuggingOptions] =
    React.useState(false);

  const [uiResult, setUiResult] = React.useState(createEmptyUiResult(null, []));

  React.useEffect(() => {
    createUiResult(
      compareCycleAtMomentsStr,
      cycleAtMomentsFromTool,
      leadCycleSpeed,
      advanceAtSweetScent,
    ).then((uiResult) => {
      setUiResult(uiResult);
    });
  }, [
    compareCycleAtMomentsStr,
    JSON.stringify(cycleAtMomentsFromTool),
    leadCycleSpeed,
    setUiResult,
    advanceAtSweetScent,
  ]);

  const fields: Field[] = [
    {
      label: "Display debugging options?",
      input: (
        <Switch
          onChange={(val) => {
            setDisplayDebuggingOptions(val);
          }}
        />
      ),
    },
    {
      label: (
        <>
          Copy-paste the JSON generated by this{" "}
          <a href="https://raw.githubusercontent.com/RainingChain/pk_emu_scripts/refs/heads/main/Gen3/E_wild_cycle_at_moment.lua">
            lua script
          </a>{" "}
          after a wild encounter to compare with the tool results.
        </>
      ),
      key: "compareCycleAtMomentsStr",
      direction: "column" as const,
      input: (
        <TextArea
          rows={5}
          onChange={(val) => {
            setCompareCycleAtMomentsStr(val.target.value);
          }}
        />
      ),
      show: displayDebuggingOptions,
    },
  ];

  const resultFields: Field[] = [
    {
      label: "Cycle at start of Sweet Scent",
      input: formatLargeInteger(uiResult.cycleAtSweetScent),
    },
    {
      label: "Method hit according to JSON (emu)",
      input: `${uiResult.methodFromJson}`,
      show: uiResult.methodFromJson != null,
    },
    {
      label: "Method hit predicted by Webtool",
      input: `${uiResult.methodFromTool}`,
      show: uiResult.methodFromTool != null,
    },
  ];

  return (
    <>
      <FormFieldTable fields={fields} />
      {displayDebuggingOptions && (
        <div>
          <strong>Use case:</strong> Detect when the tool miscalculates cycles
          and simplify its calibration by developpers.
        </div>
      )}
      {displayDebuggingOptions && (
        <Flex vertical gap={10}>
          {uiResult.errorMsg !== "" && (
            <Typography.Text type="danger">{uiResult.errorMsg}</Typography.Text>
          )}
          <FormFieldTable fields={resultFields} />
          <ResultTable<UiResultCycleAtMoment>
            columns={uiCycleAtMomentColumns}
            rowKey="uid"
            dataSource={uiResult.uiCycleAtMoments}
          />
        </Flex>
      )}
    </>
  );
};
