import { CycleAtMoment, rngTools } from "~/rngTools";
import {
  Field,
  ResultColumn,
  FormFieldTable,
  ResultTable,
  Switch,
  Flex,
  Typography,
} from "~/components";
import React from "react";
import { TextArea } from "~/components/textArea";
import { formatLargeInteger } from "~/utils/formatLargeInteger";
import {
  fillDataFromTool,
  fillDataFromJson,
  calculateDataDiff,
  cycleAtMomentsFromJsonSchema,
  type UiResult,
  type UiResultCycleAtMoment,
  type CycleAtMomentsJson,
} from "./wild3CycleAtMomentsFormatting";

const uiCycleAtMomentColumns: ResultColumn<UiResultCycleAtMoment>[] = [
  {
    title: "Moment",
    dataIndex: "moment",
  },
  {
    type: "group",
    title: "Data predicted by Webtool",
    columns: [
      {
        title: "Frame",
        key: "dataFromTool_Frame",
        dataIndex: "dataFromTool",
        render: (dataFromTool) => {
          return formatLargeInteger(dataFromTool.frame);
        },
      },
      {
        title: "Cycle",
        key: "dataFromTool_Cycle",
        dataIndex: "dataFromTool",
        render: (dataFromTool) => {
          return formatLargeInteger(dataFromTool.cycle);
        },
      },
      {
        title: (
          <>
            Cycle from
            <br />
            Sweet Scent start
            <br />
            excluding Vblank
          </>
        ),
        key: "dataFromJson_CycleSweetScent",
        dataIndex: "dataFromTool",
        render: (dataFromTool) => {
          return formatLargeInteger(dataFromTool.cycleFromSweetScent);
        },
      },
      {
        title: "Increment",
        key: "dataFromJson_Increment",
        dataIndex: "dataFromTool",
        render: (dataFromTool) => {
          return `+${formatLargeInteger(dataFromTool.cycleFromSweetScentIncrement)}`;
        },
      },
    ],
  },
  {
    type: "group",
    title: "Data from JSON generated by emulator (lua)",
    columns: [
      {
        title: "Frame",
        key: "dataFromJson_Frame",
        dataIndex: "dataFromJson",
        render: (dataFromJson) => {
          return formatLargeInteger(dataFromJson.frame);
        },
      },
      {
        title: "Cycle",
        key: "dataFromJson_Cycle",
        dataIndex: "dataFromJson",
        render: (dataFromJson) => {
          return formatLargeInteger(dataFromJson.cycle);
        },
      },
      {
        title: (
          <>
            Cycle from
            <br />
            Sweet Scent start
            <br />
            excluding Vblank
          </>
        ),
        key: "dataFromJson_CycleSweetScent",
        dataIndex: "dataFromJson",
        render: (dataFromJson) => {
          return formatLargeInteger(dataFromJson.cycleFromSweetScent);
        },
      },
      {
        title: "Increment",
        key: "dataFromJson_Increment",
        dataIndex: "dataFromJson",
        render: (dataFromJson) => {
          return `+${formatLargeInteger(dataFromJson.cycleFromSweetScentIncrement)}`;
        },
      },
    ],
  },
  {
    type: "group",
    title: "Webtool difference with JSON",
    columns: [
      {
        title: (
          <>
            Cycle from
            <br />
            Sweet Scent start
            <br />
            excluding Vblank
          </>
        ),
        key: "dataDiff_CycleSweetScent",
        dataIndex: "dataDiff",
        render: (dataDiff) => {
          return formatLargeInteger(dataDiff.cycleFromSweetScent);
        },
      },
      {
        title: "Increment",
        key: "dataDiff_Increment",
        dataIndex: "dataDiff",
        render: (dataDiff) => {
          const prefix = dataDiff.cycleFromSweetScentIncrement >= 0 ? "+" : "";
          return `${prefix}${formatLargeInteger(dataDiff.cycleFromSweetScentIncrement)}`;
        },
      },
    ],
  },
  {
    // Repeat the column so it also appears next to the Difference columns, to help compare.
    title: "Moment",
    key: "Moment2",
    dataIndex: "moment",
  },
];

const parseCycleAtMomentsJsonStr = (input: string) => {
  try {
    const info = JSON.parse(input);
    return cycleAtMomentsFromJsonSchema.parse(info);
  } catch {
    return null;
  }
};

type Props = {
  cycleAtMomentsFromTool: CycleAtMoment[];
  /** leadCycleSpeedFromTool is null if egg lead */
  leadCycleSpeed: number | null;
  advanceAtSweetScent: number;
};

let nextUid = 0;

const createEmptyUiResult = (
  json: CycleAtMomentsJson | null,
  cycleAtMomentsFromToolForFallback: CycleAtMoment[],
): UiResult => {
  const moments =
    json == null
      ? cycleAtMomentsFromToolForFallback.map((cam) => cam.moment)
      : json.cycleAtMoments
          .filter((cam) => cam.moment !== "VblankIntr_End")
          .map((cam) => cam.moment);

  const uiCycleAtMoments: UiResultCycleAtMoment[] = moments.map((moment) => {
    return {
      uid: nextUid++,
      moment,
      dataFromJson: {
        cycle: 0,
        frame: 0,
        cycleFromSweetScent: 0,
        cycleFromSweetScentIncrement: 0,
      },
      dataFromTool: {
        cycle: 0,
        frame: 0,
        cycleFromSweetScent: 0,
        cycleFromSweetScentIncrement: 0,
      },
      dataDiff: {
        cycleFromSweetScent: 0,
        cycleFromSweetScentIncrement: 0,
      },
    };
  });

  return {
    methodFromJson: null,
    methodFromTool: null,
    cycleAtSweetScent: 0,
    frameAtSweetScent: 0,
    advanceAtSweetScent: 0,
    uiCycleAtMoments,
    vblankDurations: [],
    errorMsg: "",
  };
};

const createUiResult = async (
  compareCycleAtMomentsStr: string,
  cycleAtMomentsFromTool: CycleAtMoment[],
  leadCycleSpeedFromTool: number | null,
  advanceAtSweetScent: number,
) => {
  const json = parseCycleAtMomentsJsonStr(compareCycleAtMomentsStr);
  const uiResult = createEmptyUiResult(json, cycleAtMomentsFromTool);

  if (compareCycleAtMomentsStr !== "" && json == null) {
    uiResult.errorMsg = "Error: Invalid JSON format or content.";
  }

  if (json != null) {
    fillDataFromJson(uiResult, json);

    if (uiResult.advanceAtSweetScent !== advanceAtSweetScent) {
      uiResult.errorMsg = `Error: The advance used in the emulator ${uiResult.advanceAtSweetScent} doesn't match the advance provided on the webtool ${advanceAtSweetScent}.`;
    }

    if (leadCycleSpeedFromTool !== null) {
      const leadPIDFromJson = parseInt(json.leadPID, 16);

      const leadCycleSpeedFromJson = isNaN(leadPIDFromJson)
        ? 0
        : await rngTools.calculate_pid_speed(leadPIDFromJson);

      if (leadCycleSpeedFromJson !== leadCycleSpeedFromTool) {
        uiResult.errorMsg =
          "Error: The lead used in the emulator doesn't match the lead provided on the webtool.";
      }
    }
  }

  fillDataFromTool(uiResult, cycleAtMomentsFromTool);
  calculateDataDiff(uiResult);

  return uiResult;
};

export const Wild3CycleAtMoments = ({
  cycleAtMomentsFromTool,
  leadCycleSpeed,
  advanceAtSweetScent,
}: Props) => {
  const [compareCycleAtMomentsStr, setCompareCycleAtMomentsStr] =
    React.useState("");

  const [displayDebuggingOptions, setDisplayDebuggingOptions] =
    React.useState(false);

  const [uiResult, setUiResult] = React.useState(createEmptyUiResult(null, []));

  React.useEffect(() => {
    const cyclesWithSweetScent = [
      { moment: "SweetScentWildEncounter" as const, cycle: 0 },
      ...cycleAtMomentsFromTool,
    ];
    createUiResult(
      compareCycleAtMomentsStr,
      cyclesWithSweetScent,
      leadCycleSpeed,
      advanceAtSweetScent,
    ).then((uiResult) => {
      setUiResult(uiResult);
    });
  }, [
    compareCycleAtMomentsStr,
    cycleAtMomentsFromTool,
    leadCycleSpeed,
    setUiResult,
    advanceAtSweetScent,
  ]);

  const fields: Field[] = [
    {
      label: "Display debugging options?",
      input: (
        <Switch
          onChange={(val) => {
            setDisplayDebuggingOptions(val);
          }}
        />
      ),
    },
    {
      label: (
        <>
          Copy-paste the JSON generated by this{" "}
          <a href="https://raw.githubusercontent.com/RainingChain/pk_emu_scripts/refs/heads/main/Gen3/E_wild_cycle_at_moment.lua">
            lua script
          </a>{" "}
          after a wild encounter to compare with the tool results.
        </>
      ),
      key: "compareCycleAtMomentsStr",
      direction: "column" as const,
      input: (
        <TextArea
          rows={5}
          onChange={(val) => {
            setCompareCycleAtMomentsStr(val.target.value);
          }}
        />
      ),
      show: displayDebuggingOptions,
    },
  ];

  const resultFields: Field[] = [
    {
      label: "Cycle at start of Sweet Scent",
      input: formatLargeInteger(uiResult.cycleAtSweetScent),
    },
    {
      label: "Method hit according to JSON (emu)",
      input: `${uiResult.methodFromJson}`,
      show: uiResult.methodFromJson != null,
    },
    {
      label: "Method hit predicted by Webtool",
      input: `${uiResult.methodFromTool}`,
      show: uiResult.methodFromTool != null,
    },
  ];

  return (
    <>
      <FormFieldTable fields={fields} />
      {displayDebuggingOptions && (
        <div>
          <strong>Use case:</strong> Detect when the tool miscalculates cycles
          and simplify its calibration by developpers.
        </div>
      )}
      {displayDebuggingOptions && (
        <Flex vertical gap={10}>
          {uiResult.errorMsg !== "" && (
            <Typography.Text type="danger">{uiResult.errorMsg}</Typography.Text>
          )}
          <FormFieldTable fields={resultFields} />
          <ResultTable<UiResultCycleAtMoment>
            columns={uiCycleAtMomentColumns}
            rowKey="uid"
            dataSource={uiResult.uiCycleAtMoments}
          />
        </Flex>
      )}
    </>
  );
};
