use serde::{Deserialize, Serialize};
use tsify::Tsify;
use wasm_bindgen::prelude::*;

use crate::gen3::{
    BASE_LEAD_PID_MOD_24_CYCLES, COMMON_LEAD_RANGE, CycleAndModCount, CycleAndModRange,
    CycleCounter, FASTEST_MODULO_CYCLE_24, Gen3Lead, INFINITE_CYCLE,
    MOST_PROBABLE_PRE_SWEET_SCENT_CYCLE, Moment, SLOWEST_MODULO_CYCLE_24, VBLANK_FREQ, Wild3Action,
    Wild3GeneratorCycleOpts, Wild3GeneratorOptions, get_min_mid_max_pre_sweet_scent_cycle,
    get_min_mid_max_vblank_cycle_duration, is_method_possible_to_trigger,
};

#[derive(Default, Debug, Clone, PartialEq, Tsify, Serialize, Deserialize)]
#[tsify(into_wasm_abi, from_wasm_abi)]
pub enum CycleFrameCounterOption {
    #[default]
    Inactive,
    MinMaxRange,
    DetailedBreakdown {
        lead_cycle_spd: usize,
        initial_cycle_frame: CycleFrame,
        vblank_cycles: Vec<usize>,
    },
}

#[derive(Default, Debug, Clone, Copy, PartialEq, Tsify, Serialize, Deserialize)]
#[tsify(into_wasm_abi, from_wasm_abi)]
pub struct CycleFrame {
    pub cycle: usize,
    pub frame: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Tsify, Serialize, Deserialize)]
#[tsify(into_wasm_abi, from_wasm_abi)]
pub struct CycleFrameMoment {
    pub cycle: usize,
    pub frame: usize,
    pub moment: Moment,
}

impl CycleFrame {
    pub fn add_cycle(&mut self, cycle: usize) {
        self.cycle += cycle;
        while self.cycle > VBLANK_FREQ {
            self.cycle -= VBLANK_FREQ;
            self.frame += 1;
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Tsify, Serialize, Deserialize)]
#[tsify(into_wasm_abi, from_wasm_abi)]
pub struct MinMaxCycleFrame {
    // assumes min_lead_cycle_spd
    pub min_cycle: CycleFrame,
    // assumes max_lead_cycle_spd
    pub max_cycle: CycleFrame,
    pub min_lead_cycle_spd: usize,
    pub max_lead_cycle_spd: usize,
}

impl MinMaxCycleFrame {
    pub fn new_inactive() -> Self {
        Self {
            min_cycle: CycleFrame { cycle: 0, frame: 0 },
            max_cycle: CycleFrame { cycle: 0, frame: 0 },
            min_lead_cycle_spd: 0,
            max_lead_cycle_spd: 0,
        }
    }

    pub fn new(
        is_egg_lead: bool,
        action: Wild3Action,
        consider_rng_manipulated_lead_pid: bool,
    ) -> Self {
        let (min_cycle, _, max_cycle) = get_min_mid_max_pre_sweet_scent_cycle(action);
        Self {
            min_cycle: CycleFrame {
                cycle: min_cycle,
                frame: 0,
            },
            max_cycle: CycleFrame {
                cycle: max_cycle,
                frame: 0,
            },
            min_lead_cycle_spd: if is_egg_lead {
                0
            } else if consider_rng_manipulated_lead_pid {
                FASTEST_MODULO_CYCLE_24
            } else {
                COMMON_LEAD_RANGE.start
            },
            max_lead_cycle_spd: if is_egg_lead {
                0
            } else if consider_rng_manipulated_lead_pid {
                SLOWEST_MODULO_CYCLE_24
            } else {
                COMMON_LEAD_RANGE.end
            },
        }
    }
    pub fn add_cycle(&mut self, cycle: usize) {
        self.min_cycle.add_cycle(cycle);
        self.max_cycle.add_cycle(cycle);
    }
    pub fn add_mod(&mut self, lead_pid_mod: usize) {
        self.min_cycle
            .add_cycle(lead_pid_mod * self.min_lead_cycle_spd);
        self.max_cycle
            .add_cycle(lead_pid_mod * self.max_lead_cycle_spd);
    }
    pub fn can_vblank_occur_soon(&self, cycle_range: usize) -> bool {
        if self.max_cycle.frame > self.min_cycle.frame {
            return true;
        }
        self.max_cycle.cycle > VBLANK_FREQ - cycle_range
    }
}

#[derive(Debug, Clone, Tsify, Serialize, Deserialize)]
#[tsify(into_wasm_abi, from_wasm_abi)]
pub enum CycleFrameCounter {
    // Ignore cycle counting. All methods are possibles and likelihood can't be determined.
    Inactive,

    // The main goal is to determine whether a method can be triggered or not.
    // It also gives approximative likelihood for each method.
    MinMaxRange {
        min_max_cycles: MinMaxCycleFrame,
        cycle_instability: f32,
        base_cycle_count: usize,
        lead_pid_mod_count: usize,
    },

    // It is used to debug issues with the cycle counter, by reproducing a very specific case then
    // comparing each CycleFrameMoment of the rust generator with the CycleFrameMoment generated by
    // the emulated game (extracted via a lua script).
    DetailedBreakdown {
        lead_cycle_spd: usize,
        current_cycle: CycleFrame,
        vblank_cycles: Vec<usize>,
        cycle_at_moments: Vec<CycleFrameMoment>,
    },
}

impl CycleFrameCounter {
    pub fn new(opts: &Wild3GeneratorOptions) -> Self {
        if !opts.cycle_opts.consider_cycles {
            CycleFrameCounter::Inactive
        } else if opts.cycle_opts.generate_cycle_at_moment {
            CycleFrameCounter::new_for_detailed_breakdown(opts.action, &opts.cycle_opts)
        } else {
            CycleFrameCounter::new_for_min_max_range(
                opts.lead == Gen3Lead::Egg,
                opts.action,
                opts.cycle_opts.consider_rng_manipulated_lead_pid,
            )
        }
    }
    pub fn new_for_detailed_breakdown(
        action: Wild3Action,
        cycle_opts: &Wild3GeneratorCycleOpts,
    ) -> Self {
        Self::DetailedBreakdown {
            lead_cycle_spd: cycle_opts.lead_cycle_spd.unwrap_or(775),
            current_cycle: CycleFrame {
                cycle: cycle_opts
                    .initial_cycle_at_sweet_scent
                    .unwrap_or(get_min_mid_max_pre_sweet_scent_cycle(action).1),
                frame: 0,
            },
            vblank_cycles: cycle_opts.vblank_cycles.clone().unwrap_or_default(),
            cycle_at_moments: vec![],
        }
    }
    pub fn new_for_min_max_range(
        is_egg_lead: bool,
        action: Wild3Action,
        consider_rng_manipulated_lead_pid: bool,
    ) -> Self {
        CycleFrameCounter::MinMaxRange {
            min_max_cycles: MinMaxCycleFrame::new(
                is_egg_lead,
                action,
                consider_rng_manipulated_lead_pid,
            ),
            cycle_instability: 0.0,
            base_cycle_count: 0,
            lead_pid_mod_count: 0,
        }
    }
    pub fn add(&mut self, cycle: usize, lead_pid_mod: usize) {
        match self {
            CycleFrameCounter::Inactive => {}
            CycleFrameCounter::DetailedBreakdown { lead_cycle_spd, .. } => {
                let total = cycle + lead_pid_mod * *lead_cycle_spd;
                self.add_cycle(total);
            }
            CycleFrameCounter::MinMaxRange { .. } => {
                self.add_cycle(cycle);
                self.add_mod(lead_pid_mod);
            }
        }
    }
    pub fn add_cycle(&mut self, cycle: usize) {
        match self {
            CycleFrameCounter::Inactive => {}
            CycleFrameCounter::DetailedBreakdown {
                current_cycle,
                vblank_cycles,
                ..
            } => {
                current_cycle.cycle += cycle;
                while current_cycle.cycle > VBLANK_FREQ {
                    current_cycle.cycle -= VBLANK_FREQ;
                    current_cycle.cycle += vblank_cycles
                        .get(current_cycle.frame)
                        .copied()
                        .unwrap_or_else(|| get_min_mid_max_vblank_cycle_duration().1);
                    current_cycle.frame += 1;
                }
            }
            CycleFrameCounter::MinMaxRange {
                base_cycle_count,
                min_max_cycles,
                ..
            } => {
                *base_cycle_count += cycle;
                min_max_cycles.add_cycle(cycle);
            }
        }
    }
    pub fn add_mod(&mut self, lead_pid_mod: usize) {
        match self {
            CycleFrameCounter::Inactive => {}
            CycleFrameCounter::DetailedBreakdown { lead_cycle_spd, .. } => {
                let cycle = lead_pid_mod * *lead_cycle_spd;
                self.add_cycle(cycle);
            }
            CycleFrameCounter::MinMaxRange {
                lead_pid_mod_count,
                min_max_cycles,
                ..
            } => {
                *lead_pid_mod_count += lead_pid_mod;
                min_max_cycles.add_mod(lead_pid_mod);
            }
        }
    }
    pub fn on_moment_reached(&mut self, moment: Moment) {
        if let Self::DetailedBreakdown {
            current_cycle,
            cycle_at_moments,
            ..
        } = self
        {
            cycle_at_moments.push(CycleFrameMoment {
                cycle: current_cycle.cycle,
                frame: current_cycle.frame,
                moment,
            });
        }
    }
    /** can a vblank occurs between now and the next <cycle_range> cycles */
    pub fn can_vblank_occur_soon(&self, cycle_range: usize) -> bool {
        match self {
            CycleFrameCounter::Inactive => true,
            CycleFrameCounter::DetailedBreakdown { current_cycle, .. } => {
                cycle_range > VBLANK_FREQ.saturating_sub(current_cycle.cycle)
            }
            CycleFrameCounter::MinMaxRange { min_max_cycles, .. } => {
                min_max_cycles.can_vblank_occur_soon(cycle_range)
            }
        }
    }
    pub fn is_possible_that_no_vblank_yet(&self) -> bool {
        match self {
            CycleFrameCounter::Inactive => true,
            CycleFrameCounter::DetailedBreakdown { current_cycle, .. } => current_cycle.frame == 0,
            CycleFrameCounter::MinMaxRange { min_max_cycles, .. } => {
                min_max_cycles.min_cycle.frame == 0
            }
        }
    }
    pub fn can_generate_method(&self, opts: &Wild3GeneratorOptions, len: usize) -> bool {
        if opts.cycle_opts.generate_even_if_impossible {
            return true;
        }

        match self {
            CycleFrameCounter::Inactive => true,
            CycleFrameCounter::DetailedBreakdown { .. } => {
                if len == INFINITE_CYCLE {
                    self.is_possible_that_no_vblank_yet()
                } else {
                    self.can_vblank_occur_soon(len)
                }
            }
            CycleFrameCounter::MinMaxRange { .. } => {
                if opts.cycle_opts.lead_cycle_spd.is_some()
                    || !opts.cycle_opts.consider_rng_manipulated_lead_pid
                {
                    return is_method_possible_to_trigger(
                        &self.create_cycle_range(len),
                        opts.action,
                        opts.lead == Gen3Lead::Egg,
                        opts.cycle_opts.consider_rng_manipulated_lead_pid,
                        opts.cycle_opts.lead_cycle_spd,
                    );
                }
                if len == INFINITE_CYCLE {
                    self.is_possible_that_no_vblank_yet()
                } else {
                    self.can_vblank_occur_soon(len)
                }
            }
        }
    }
    pub fn create_cycle_range(&self, len: usize) -> CycleAndModRange {
        match self {
            CycleFrameCounter::Inactive => CycleAndModRange::new(0, 0, 0),
            CycleFrameCounter::DetailedBreakdown { .. } => {
                CycleAndModRange::new(self.get_current_cycle_count(), 0, len)
            }
            CycleFrameCounter::MinMaxRange {
                lead_pid_mod_count, ..
            } => CycleAndModRange::new(self.get_current_cycle_count(), *lead_pid_mod_count, len),
        }
    }
    pub fn to_cycle_counter(&self) -> CycleCounter {
        match self {
            CycleFrameCounter::Inactive => CycleCounter::default(),
            CycleFrameCounter::DetailedBreakdown { .. } => CycleCounter {
                cycle: CycleAndModCount {
                    cycle: self.get_current_cycle_count(),
                    lead_pid_mod: 0,
                },
                ..Default::default()
            },
            CycleFrameCounter::MinMaxRange {
                lead_pid_mod_count,
                cycle_instability,
                ..
            } => CycleCounter {
                cycle: CycleAndModCount {
                    cycle: self.get_current_cycle_count(),
                    lead_pid_mod: *lead_pid_mod_count,
                },
                cycle_instability: *cycle_instability,
                ..Default::default()
            },
        }
    }

    pub fn get_current_cycle_count(&self) -> usize {
        match self {
            CycleFrameCounter::Inactive => 0,
            CycleFrameCounter::DetailedBreakdown { current_cycle, .. } => {
                current_cycle.frame * VBLANK_FREQ + current_cycle.cycle
            }
            CycleFrameCounter::MinMaxRange {
                base_cycle_count,
                lead_pid_mod_count,
                ..
            } => *base_cycle_count + *lead_pid_mod_count * BASE_LEAD_PID_MOD_24_CYCLES,
        }
    }
    pub fn set_cycle_instability(&mut self, instability: f32) {
        match self {
            CycleFrameCounter::Inactive | CycleFrameCounter::DetailedBreakdown { .. } => {}
            CycleFrameCounter::MinMaxRange {
                cycle_instability, ..
            } => *cycle_instability = instability,
        }
    }
    pub fn get_cycle_instability(&self) -> f32 {
        match self {
            CycleFrameCounter::Inactive | CycleFrameCounter::DetailedBreakdown { .. } => 0.0,
            CycleFrameCounter::MinMaxRange {
                cycle_instability, ..
            } => *cycle_instability,
        }
    }

    pub fn get_cycle_at_moments(&self) -> Vec<CycleFrameMoment> {
        match self {
            CycleFrameCounter::Inactive | CycleFrameCounter::MinMaxRange { .. } => vec![],
            CycleFrameCounter::DetailedBreakdown {
                cycle_at_moments, ..
            } => cycle_at_moments.clone(),
        }
    }
}
