name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy_app:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: "prod"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.86.0
        with:
          targets: wasm32-unknown-unknown

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install prebuilt wasm-pack
        run: |
          set -e
          VERSION=0.14.0
          ARTIFACT=wasm-pack-v${VERSION}-x86_64-unknown-linux-musl
          URL="https://github.com/wasm-bindgen/wasm-pack/releases/download/v${VERSION}/${ARTIFACT}.tar.gz"
          SHA_URL="${URL}.sha256"

          echo "Downloading wasm-pack ${VERSION}..."
          curl -fsSL $URL -o wasm-pack.tar.gz
          curl -fsSL $SHA_URL -o wasm-pack.sha256

          echo "Verifying checksum..."
          sha256sum -c wasm-pack.sha256

          echo "Extracting..."
          tar -xzf wasm-pack.tar.gz --strip-components=1 -C /usr/local/bin ${ARTIFACT}/wasm-pack

      - name: Test rng_tools
        run: cargo test --manifest-path rng_tools/Cargo.toml

      - name: Build rng_tools
        run: bun run build:rng_tools

      - name: Get Git Commit Info
        run: |
          echo "ISO_BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check code
        run: bun run lint

      - name: Build
        run: bun run build
        env:
          CI: true
          VITE_GIT_COMMIT: ${{ env.GIT_COMMIT }}
          VITE_ISO_BUILD_DATE: ${{ env.ISO_BUILD_DATE }}
          VITE_AMPLITUDE_API_KEY: ${{ vars.VITE_AMPLITUDE_API_KEY }}
          VITE_DISCORD_HALL_OF_FAME_SUPPORTERS: ${{ vars.VITE_DISCORD_HALL_OF_FAME_SUPPORTERS }}
          VITE_PATREON_HALL_OF_FAME_SUPPORTERS: ${{ vars.VITE_PATREON_HALL_OF_FAME_SUPPORTERS }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          clean: false
