name: Main checks

on:
  push:
    branches:
      - main

jobs:
  lint-build-deploy:
    name: Lint, build, and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Check formatting
        run: yarn format:check

      - name: Build
        run: yarn build
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }} # It's really not much of a secret

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
