name: Non-main checks

on:
  push:
    branches:
      - '!main'

jobs:
  lint-check-format-build:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Check formatting
        run: yarn format:check
